### ISSUE TITLE
[dashboard] Plugin binding query not at right place (I've got the 100th !)

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#100]
The binding query concerns only manually device creation. So it must be called when user clic on manually device creation button, not on display on the plugin page of the dashboard.
If done, the actually message in case of binding error is enough and #99 can be closed.

**Comment by jano42** [comment]
The binding query are not made only for "manually device creation"

There are two types of binding
 * system binding : always available it asks for a "global" dynamic value (network card list for example)
 * plugin binding : only available when plugin is started. The values are provided by the plugin instance

In fact each time there is a configuration schema, the binding can be used. The only exception is "plugin binding" in "plugin configuration".

So "plugin binding" can be used for
 * manually device creation
 * extra commands
