### ISSUE TITLE
Plugin MailSender : crash under Windows in release build (missing DLL)

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#104]
![image](https://cloud.githubusercontent.com/assets/6855339/15587494/bf78d04e-2389-11e6-9db9-6e3ef9e543fe.png)

**Comment by sgallou** [comment]
ssleay32.dll is missing too.

**Comment by sgallou** [comment]
vsinit.dll too...

**Comment by jmberhault** [comment]
OpenSSL choose be installed with the correct installation option : 
_During the installation phase, choose the option for copy OpenSSL DLLs to : "The Windows system directory"._
