### ISSUE TITLE
Plugin ZWave : Restart of ZWave controller doesn't work (on Windows)

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#105]
To recover the plugin blocked in association mode, I tried to restart it from dashboard. Windows played sound as the dongle was unplugged, and the dongle was not seen anymore from Windows.
Need to physically unplug/re-plug the dongle to recover.

**Comment by jano42** [comment]
It seems that soft reseting, just reboot internal stick chip.

Remove "bug" tag, because it is more misunderstanding than an issue

**Comment by sgallou** [comment]
Duplicate with #196

**Comment by jano42** [comment]
The user have to physically disconnect the USB stick and reconnect it before restarting plugin instance.
