### ISSUE TITLE
[Plugin MailSender] DLL are missing (on Windows)

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#113]
Don't work out-of-the-box : some DLL are missing after a fresh compilation (same in debug or release configuration) : all external dependancies of PocoNetSsl.dll library : libeay32.dll, ssleay32.dll...
Need to be deployed at compilation time.
Need to be deployed by installer

**Comment by jmberhault** [comment]
OpenSSL choose be installed with the correct installation option : 
_During the installation phase, choose the option for copy OpenSSL DLLs to : "The Windows system directory"._

**Comment by jano42** [comment]
This trick must not be the official bug fix.

The cmakelist should already handle this problem. There is a case that is not handled correctly by CMake

**Comment by sgallou** [comment]
Not a bug, OPENSSL_ROOT_DIR was not correctly set in my CMakeUserConfig.txt
