### ISSUE TITLE
Plugin name with simple quote make server crash

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#123]
In french, the mail sender default name is "Envoi d'email", which make server crash (in database insertion) because of the simple quote :

08:39:37 :  : [Error] : Query failed :
Query:  INSERT INTO Plugin (displayName,type,configuration,autoStart)  VALUES  ('Envoi d\'email','MailSender','{"Sender"
:"dfjklsd@qsdklmq.com","account":{"content":{"gmail":{"content":{"password":"VB5T"},"radio":"true"},"outlook":{"content"
:{"password":""},"radio":"false"},"ovh":{"content":{"password":""},"radio":"false"},"yahoo":{"content":{"password":""},"
radio":"false"},"other":{"content":{"SMTPServer":"","SMTPPort":"587","Security":"none","authentication":{"content":{"use
r":"","password":""},"checkbox":"false"}},"radio":"false"}},"activeSection":"gmail"}}
','1')
Error : near "email": syntax error

**Comment by jano42** [comment]
Which database (sqlite, pgsql) ?
On which branch ?

Please clarify

**Comment by jmberhault** [comment]
I have notice this also with in the main branch with sqlite. I have reproduce it with a new database, when I create plugins.

**Comment by jano42** [comment]
Fix by by commit 607cc1593eaa900c8445072e4ccbe3243570a25b
