### ISSUE TITLE
[Devices dashboard page] plugin state devices must not be removable

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#126]
The trash button is active for the fakePlugin device here (must be disabled) :

![image](https://cloud.githubusercontent.com/assets/6855339/16370268/87fcffd2-3c3e-11e6-96a9-a828fd6ecf85.png)

**Comment by jano42** [comment]
Don't know why we should disable it.

Why should we do a special case for this plugin ? Plus, the plugin is only visible in developerMode, so really no interest to do this.
