### ISSUE TITLE
Plugins : sometimes one plugin crashed

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#132]
sometimes one plugin crashed after a while. 
This trouble appears sometimes since separated processes.

Below logs from my raspberry Pi.

Server logs
=========

22:01:19 : plugin/teleinfo #11 : [Error] : Call was : deviceExists(031428097115)
22:01:20 : plugin/teleinfo #11 : [Information] : Close message queues
22:01:20 : plugin/teleinfo #11 : [Error] : teleinfo crashed with exception : No answer from Yadoms when sending message 4
22:01:20 :  : [Error] : Stop plugin instance #11 because of error : Call was : deviceExists(031428097115)teleinfo crashed with exception : No answer from Yadoms when sending message 4, return code = 2

22:02:24 : plugin/rfxcom #8 : [Error] : Call was : deviceExists(2.287)
22:02:25 : plugin/rfxcom #8 : [Information] : Close message queues
22:02:25 : plugin/rfxcom #8 : [Error] : rfxcom crashed with exception : No answer from Yadoms when sending message 4
22:02:25 :  : [Error] : Stop plugin instance #8 because of error : Invalid RfxCom message received, unknown packet type d5Invalid RfxCom message received, unknown packet type 00Invalid RfxCom message received, unknown packet type d5Invalid RfxCom message received, unknown packet type d5Invalid RfxCom message received, unknown packet type d5No answer received, try to reconnect in a while...Call was : deviceExists(2.287)rfxcom crashed with exception : No answer from Yadoms when sending message 4, return code = 2

Plugins Logs
==========

2016/06/30 22:02:24 : [ERROR] Call was : deviceExists(2.287)
2016/06/30 22:02:25 : [INFORMATION] Close message queues
2016/06/30 22:02:25 : [ERROR] rfxcom crashed with exception : No answer from Yadoms when sending message 4

2016/06/30 22:01:19 : [ERROR] Call was : deviceExists(031428097115)
2016/06/30 22:01:20 : [INFORMATION] Close message queues
2016/06/30 22:01:20 : [ERROR] teleinfo crashed with exception : No answer from Yadoms when sending message 4

**Comment by sgallou** [comment]
At startup, some plugins can crash because Yadoms server is overloaded.
We probably have to change the Yadoms server startup sequence to not start all at same time but first plugins management, then rules and web server (will also solve the case of a rule start to use an not yet started plugin).
