### ISSUE TITLE
Web client bad behaviour when a plugin is malformed

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#134]
If a plugin is mal-formed (package.json not compliant as expected, ie without configurationSchema tag), when we try to intantiate it by plugin dashboard, nothing is done and no error notification is poped.

An error notification must be pop in this case (with simple standard text, like "unable to create plugin")

**Comment by jano42** [comment]
Please give a sample package.json which illustrate the prolem.

In fact, depending on the package.json malformation we could have different behaviors.

**Comment by jano42** [comment]
Fixed in device_configuration branch
