### ISSUE TITLE
JSON : empty collection

### ISSUE THREAD

**Issue by jano42** [Yadoms/yadoms#136]
When the REST server should answer with an empty collection; it provides a bad format
#### Example : listing recipients, if no recipient exists in database

GET : "/rest/recipient"

Results:

``` json
{
   "result": "true",
   "message": "",
   "data": {
      "recipient": ""
   }
}
```

The recipient value is empty string **""** and should be **[ ]**

**Comment by jano42** [comment]
This is due to boost library.

Yadoms uses boost::property_tree as hierarchical container and parse/generate JSON format.
In fact, after googling, the global answer is : "boost arrays into json are hacks;...., empty collection are not handled,.... use a dedicated JSON library"

So two choices
 1. bypass this problem (the javascript should handle empty string "" instead of empty collection []). Mostly done.
 2. use another library (poco::json,...) instead of boost::property_tree

**Comment by sgallou** [comment]
Note that it already exist a unit-test (SimpleConstruction in TestDataContainer.cpp, that fails) in Yadoms unit-tests collection that handle a similar problem : a tree created from a non-JSON string like "1" doesn't throw, while serializing the obtained object to JSON throws.

**Comment by sgallou** [comment]
Will be fixed with JSON refactoring by rapidjson
