### ISSUE TITLE
[web client - configuration] Too much time to load configuration data cause exceptions

### ISSUE THREAD

**Issue by jano42** [Yadoms/yadoms#14]
I have a chart with 3 series of data. When I edit the chart configuration, configured devices are immediately displayed, but keywords are delayed (empty for approx. 1 second for each, so approx 3 seconds to populate all the configuration fields). If I click OK too quick, configuration becomes corrupted, and widget generate exception.
This slowly data loading come probably from my R-PI 1, and the heavy configuration of the web client (2 pages, 3 charts, 3 gauges, 1 thermometer, 1 numeric, 3 indicators, 1 switch).

I think that OK button should be grayed until all fields are populated from the existing configuration.

Reported by: sgallou

**Comment by jmberhault** [comment]
This issue is assumed to be corrected with the #38.
