### ISSUE TITLE
Widget : Configuration access with a smartphone

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#140]
With a smartphone, the configuration access of widgets is impossible. Each time we try to select the button, the action move a little bit the widget. 

with a tablet, the phenomena could appears, but the configuration could be accessed after one or two attempts.

With a PC or a laptop, the problem doesn't exist (with a mouse pointer).

One explanation of this behavior could be the small size of the button "configuration".

**Comment by sgallou** [comment]
Duplicate with #185
