### ISSUE TITLE
Edge browser

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#142]
Pages could not be opened with Edge/Windows 10 : 

![5341711c](https://cloud.githubusercontent.com/assets/16737541/18641806/7e4b48fc-7e9e-11e6-8070-718119a97133.png)

Yadoms is running with a Pi2.

**Comment by jmberhault** [comment]
This trouble disappears since the update of edge to the revision 25.10586.0.0. Errors come from source maps that are not present for the development tab. Theses errors only exist for the bootstrap library.

**Comment by jano42** [comment]
Same as #177 
fixed
