### ISSUE TITLE
Devices : rarely, after renaming a device, it is not present in the list

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#145]
![renommage erreur](https://cloud.githubusercontent.com/assets/16737541/19221389/c0ee6956-8e42-11e6-9c19-06a66f1f27a4.png)

In this screen shot, we could see the device into browser console log.

After clicking a new time the "equipments" button, the missing device is present in the list.

**Comment by sgallou** [comment]
@jmberhault Not reproduced for long time at my side. Did you reproduce it recently ?

**Comment by jmberhault** [comment]
This appends very rarely. It's depend of the number of devices displayed into the devices list. (more equipment, more the behaviour appears)
Closed in branch 2_0_0.
