### ISSUE TITLE
GUI -> Devices : Manual creation of a device doesn't work

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#146]
After clicking create a equipment attached to the RFXCOM.

![manual creation of a equipment](https://cloud.githubusercontent.com/assets/16737541/19221408/5d9f81e0-8e43-11e6-86fa-607f5a6ea18f.png)

The parameter pass through PluginInstanceManager looks to be undefined or null.

**Comment by sgallou** [comment]
var pluginId = $("select#associatedPluginTypeList").val(); fails to get the pluginId (set to undefined).

See device-add-manually.html, line 62

I think last commit on this file (11e3b5fa7cd79794376be80db966ea53efb53c0f, on 12/06/2016 17:13:11) makes the regression.
