### ISSUE TITLE
Plugin/script big log display

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#150]
If user want to display a big plugin log, the log-modal is displayed with previous displayed log, until the entire log file is downloaded, which can be very long (I have a log file of 440 Mb for Megatec UPS).

Displaying log must be reworked to :
- clean content when displaying the window
- download progressively the file (at least in case of big files)

Megatec UPS logs should be maybe reworked too...

**Comment by sgallou** [comment]
SystemInformation logs also too much (95 Mb actually), should be reworked too...

**Comment by jmberhault** [comment]
Logs initially was for the trace mode.
