### ISSUE TITLE
Weather Underground : City mysteriously change

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#154]
The location entered was "Valence"; which worked for a while.
And suddenly, location becomes "Cheylade", without intervention. Log :

2016/10/19 17:52:30 : [INFORMATION] Refresh Weather Conditions
2016/10/19 18:07:30 : [INFORMATION] Observation location :Rue des Alpes, Valence,
2016/10/19 18:07:30 : [INFORMATION] Refresh Weather Conditions
2016/10/19 18:22:30 : [INFORMATION] Observation location :Rue des Alpes, Valence,
2016/10/19 18:22:30 : [INFORMATION] Refresh Weather Conditions
2016/10/19 18:22:30 : [INFORMATION] Fail to send get http request "" : . Retry in 1 minute.
2016/10/19 18:22:31 : [INFORMATION] forecast.low_temperature=7 celcius degrees
2016/10/19 18:22:31 : [INFORMATION] forecast.Rain_Day_0=0mm
2016/10/19 18:22:31 : [INFORMATION] forecast.Rain_Day_1=0mm
2016/10/19 18:22:31 : [INFORMATION] forecast.Rain_Day_2=0mm
2016/10/19 18:22:31 : [INFORMATION] Refresh Forecast Information
2016/10/19 18:23:31 : [INFORMATION] Fail to send get http request "" : . Retry in 1 minute.
2016/10/19 18:24:31 : [INFORMATION] Fail to send get http request "" : . Stop retry.
2016/10/19 18:37:30 : [INFORMATION] Observation location :Rue des Alpes, Valence,
2016/10/19 18:37:30 : [INFORMATION] Refresh Weather Conditions
2016/10/19 18:52:30 : [INFORMATION] Observation location :Cheylade, Cheylade, AUVERGNE
2016/10/19 18:52:30 : [INFORMATION] Refresh Weather Conditions
2016/10/19 19:07:30 : [INFORMATION] Observation location :Cheylade, Cheylade, AUVERGNE
2016/10/19 19:07:30 : [INFORMATION] Refresh Weather Conditions
2016/10/19 19:22:30 : [INFORMATION] Observation location :Cheylade, Cheylade, AUVERGNE

**Comment by jmberhault** [comment]
close by #fc994bc
