### ISSUE TITLE
Widgets no more refreshed on Firefox

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#156]
Found with Firefox 49.0.1.
Works well on Chrome.

A log in console (I don't know if useful) say :
"Une chaîne vide a été transmise à « getElementById()          jquery-2.2.0.min.js:2:24659"

**Comment by jano42** [comment]
Don't reproductible with Firefox 47.0.2 (the version installed on my computer) and 50.0.2 (the up to date version)

@sgallou I let you retry with newer Firefox version

**Comment by sgallou** [comment]
Also yet not reproductible... Closed...
