### ISSUE TITLE
Scripts : value conversion with no acquisition

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#162]
When a keyword is read with no acquisition (first time use), or when after a database cleanup that delete all acquisition, scripts return the following error:

2016/11/06 22:43:26 : [ERROR] Traceback (most recent call last):
2016/11/06 22:43:26 : [ERROR] File "scriptCaller.py", line 38, in <module>
2016/11/06 22:43:26 : [ERROR] script.yMain(yApi)
2016/11/06 22:43:26 : [ERROR] File "/home/pi/yadoms/builds/scripts/locals/rule_5/yadomsScript.py", line 18, in yMain
2016/11/06 22:43:26 : [ERROR] if bool(int(yApi.readKeyword(78))) == True:
2016/11/06 22:43:26 : [ERROR] ValueError: invalid literal for int() with base 10: ''

This error is normal, there is no acquisition in the database, but my rule is stopped in error state.

**Comment by sgallou** [comment]
It's a Blockly-side problem :
keyword-value-get.js must handle the case where readKeyword returns empty string. I suggest readKeyword should return a default value in this case (false for bool value, 0 for int value, etc...).

**Comment by jmberhault** [comment]
There is no error for the script, but, after the cleaning of old values, a default value is returned that not matched the last value : 
example : I have started my heater for all the winter time, after 1 month, all values into the database have been deleted, so with no values present, a default value of false is sent to script, with the effet of to stop my heater ...

**Comment by jano42** [comment]
Actually the "getKeywordValue" block, returns the last value of a keyword; or a default value (determined by Python => 0 for int, false for boolean).

It would be very difficult to change the behavior; to make it easily usable.

One of the solution, could be to make a new block "checkIfKeywordHaveData" which returns a boolean.
so scripts could be ajusted perfectly ?

**Comment by sgallou** [comment]
Fixed from RefactorLastKeywordData branch :

- Purge task no more delete last data value of each keyword
- Virtual devices have now an initial value

Merged into 2_0_0 branch by 10b469821a357e8439ad514046b6fb1629b3abae
