### ISSUE TITLE
Meteo data : wrong text encoding for city

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#169]
plugin WU + widget meteo :

![image](https://cloud.githubusercontent.com/assets/6855339/20410349/d9b15f40-ad1c-11e6-89af-0f79f1ee220f.png)

**Comment by jmberhault** [comment]
Cannot test because of an error of protobuf 2.6 : 

![utf8](https://cloud.githubusercontent.com/assets/16737541/22126629/bd1d5ca0-de98-11e6-8cea-d4fb0e35027c.png)

**Comment by sgallou** [comment]
Please test with Protobuf3 branch

**Comment by jmberhault** [comment]
In the new weatherUnderground plugin, the city field read have no emphasis. I could not reproduce the behaviour.
