### ISSUE TITLE
starting too long

### ISSUE THREAD

**Issue by jano42** [Yadoms/yadoms#170]
It could take more than one minutes until having the web server started !!

The web server should start asap, to tell the user that yadoms is not hang

**Comment by sgallou** [comment]
Yadoms need a "yadoms is starting, please wait..." page to display when plugins are starting.
We can also remove the timeout waiting plugins state running in developer mode.

**Comment by jano42** [comment]
Fixed in branch device_configuration

**Comment by sgallou** [comment]
Migrating database can also take a lot of time. Is it possible to start web server before migrating database (to show "Yadoms is starting message...") ?

**Comment by sgallou** [comment]
Not an issue
