### ISSUE TITLE
GUI-> all devices : on/off value instead of 0/1

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#171]
boolean value should be on/off, and eventually translated.

![onoff](https://cloud.githubusercontent.com/assets/16737541/20687688/cd5fc6ec-b5bd-11e6-981f-1e2beebaaa91.png)

**Comment by sgallou** [comment]
In addition, I noticed that command sent by device dashboard send "true"/"false" values while switch widget send "1"/"0".
Plugin code must support the two forms. Plugin code should not be coupled with values sent by web client.

**Comment by jano42** [comment]
[Fix by](https://github.com/Yadoms/yadoms/commit/c3e060c7e47364f83961210f313b24ddcb8282d0)
