### ISSUE TITLE
Dashboard quick navigation make several pages displayed

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#172]
When navigate accross the dashboard pages a bit quickly (or on a slow machine), the new page is added to te previous, which is not hidden.
The user test dashboard\testNavigationAccrossPages.py reproduces easily the problem, even on good machine : when clicking fast on the left menu on every entries (system conf, plugins, devices...), all pages content are displayed on the same screen :

![image](https://cloud.githubusercontent.com/assets/6855339/20832431/91dc8b8a-b88a-11e6-8905-59e9698a5105.png)

**Comment by jano42** [comment]
Should be fixed in device_configuration branch. 
@sgallou please test

**Comment by sgallou** [comment]
The fix helps but is not perfect : it makes that only one page content is displayed on the page, but some clicks seems lost. Need from time to time several clicks to change page.
Maybe should be enought for now (waiting for Angular... :-) )

**Comment by sgallou** [comment]
Reopened because on rollback on source  code

**Comment by sgallou** [comment]
Erroneous close because of returning device_configuration branch in master

**Comment by jmberhault** [comment]
fixed in branch 2_0_0 by commit 3d1867f237287e0d4bdd07fd5113477911936443
