### ISSUE TITLE
[Devices dashboard] Set keyword enum value write an integer

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#173]
When driving a enum keyword (ie for plugin fakePlugin, device fakeController1, keyword controllerValue) from the dashboard (devices page), choosing a enum value display an integer in the value column :

![setkeywordenumvalue](https://cloud.githubusercontent.com/assets/6855339/20962016/d8b760d0-bc67-11e6-8cec-57aa49ec1425.gif)

**Comment by jano42** [comment]
Fixed in device_configuration branch
