### ISSUE TITLE
[Devices dashboard] enum keyword bad friendly-name

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#176]
The enum keyword is named (friendly-name field) by the enum type name (declared in en.json in "enumerations" value) instead of the keyword name (declared by the plugin calling declareKeyword method).

Example with fake-plugin, fakeController1 device :
Regarding fake-plugin code, the unique keyword of device is declared as "controllerValue" (see sources\plugins\dev-FakePlugin\FakeController.cpp line 34).
In fake-plugin en.json file, the enum used with FakeController is declared as :
"enumerations": {
   "EFakeControllerValues": {
      "name" : "Etat controller",
      "values" : {
         "Stop": "Stop",
         "Run": "Run",
         "Back": "Back",
         "Left": "Turn Left",
         "Right": "Turn Right"
      }
   }
},

In devices dashboard, we see "Etat controller", when "controllerValue" was expected.

**Comment by jmberhault** [comment]
This issue will be closed when we integrate keyword translation. 

At this time, when the plugin create the keyword, this one is created with a friendlyName = Name. 
In the web client we display this friendlyName without any filter (no translation).

**Comment by sgallou** [comment]
Can't reproduce
