### ISSUE TITLE
Unable to click on widget configure and remove buttons with mobile device 

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#180]
In editing mode, a click on the configure or remove button selects the widget for drag and drop. Unable to configure or remove a widget. 
See on Samsung TabS under chrome

**Comment by jmberhault** [comment]
Better sensive with this commit : #5752a7f891d4292819e8fe5f7d24c62fdcf2114d
To be tested.

**Comment by jmberhault** [comment]
For big density screens, this modification is not enough. Customize and delete buttons will be redesigned.

**Comment by jmberhault** [comment]
fixed with commit 3640361e5b257282334978f8b03599d1f9394106
