### ISSUE TITLE
[Blobkly] Can not drive device anymore

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#184]
In Protobuf3 branch, with just a fakeplugin, I'm not able to drive a device with value (OK for an event).

The last block must propose a 'value' field :
![image](https://cloud.githubusercontent.com/assets/6855339/22595642/a0dc2a12-ea28-11e6-8c0f-b16952aa83c4.png)

**Comment by sgallou** [comment]
More information : changing device doesn't refresh the block (wether should have operator and value or not), but changing keyword (even if only one is present in keywords list) correctly refresh the block.

2 solutions :
* Block must be refreshed also when device is changed
* When select a device, keyword must be reset to "choose a data"

![blockly](https://cloud.githubusercontent.com/assets/6855339/22902829/bd7b2360-f236-11e6-807c-502983184319.gif)

**Comment by jano42** [comment]
Fixed in branch Protobuf3 by https://github.com/Yadoms/yadoms/commit/a43be46027c1d804b104ca73cb9332cc032801cf
