### ISSUE TITLE
PostGre databse probably fails to migrate to 3.0.0 database version

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#186]
Code used to migrate database version from 2.0.0 to 3.0.0 call specific SQLite objects. What happen with a postGreSQL database ?

Fonction : CVersion_3_0_0::UpdateFrom2_0_0
SQLite object used : sqlite::CSQLiteRequester

**Comment by jano42** [comment]
Don't understand.

If using PostgreSQL database, the object used is not sqlite::CSQLiteRequester but pgsql::CPgsqlRequester.

And from update script, line67 is for SQlite, and line76 for PostgreSQL
