### ISSUE TITLE
[Shutter widget] Bad mouse-over cursor

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#190]
Should be a hand, but still the standard arrow.
![mouseover](https://cloud.githubusercontent.com/assets/6855339/23632143/0e0b2d4e-02c1-11e7-8fd3-747f3840a26e.gif)

**Comment by jano42** [comment]
Fixed in Protobuf3 branch by copmmit https://github.com/Yadoms/yadoms/commit/06181faf9c92fac89c13f2d8f77f1c5a1e89f70b
