### ISSUE TITLE
Plugin Zwave : click configure into the device corresponding to the USB key

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#195]
![zwave2](https://cloud.githubusercontent.com/assets/16737541/24075939/39429b46-0c26-11e7-8ad4-0b588748cd37.png)

When clicking into the configure button, I found the following traces : 

20:54:51 : mainThread : [Information] : ZWave started
20:54:51 : mainThread : [Information] : CZWave is initializing
20:54:51 : ZWave : [Information] : OpenZWave notification : DriverReady
20:54:51 : ZWave : [Information] : OpenZWave notification : NodeAdded
20:54:51 : ZWave : [Information] : OpenZWave notification : NodeProtocolInfo
20:54:51 : ZWave : [Information] : ZWave : NodeProtocolInfo : Static PC Controller
20:54:51 : ZWave : [Information] : OpenZWave notification : EssentialNodeQueriesComplete
20:54:51 : ZWave : [Information] : OpenZWave notification : ValueAdded
20:54:51 : ZWave : [Information] : OpenZWave notification : NodeNaming
20:54:51 : ZWave : [Information] : ZWave : NodeNaming : id = 3729296991.1
20:54:51 : ZWave : [Information] : ZWave : NodeNaming : name = 
20:54:51 : ZWave : [Information] : ZWave : NodeNaming : manufacturer = Aeotec
20:54:51 : ZWave : [Information] : ZWave : NodeNaming : productName = Z-Stick Gen5
20:54:51 : ZWave : [Information] : ZWave : NodeNaming : productType = 0x0001
20:54:51 : ZWave : [Information] : ZWave : NodeNaming : productId = 0x005a
20:54:51 : ZWave : [Information] : OpenZWave notification : NodeQueriesComplete
20:54:51 : ZWave : [Information] : OpenZWave notification : AllNodesQueried
20:54:51 : ZWave : [Information] : OpenZWave notification : NodeQueriesComplete
20:54:51 : mainThread : [Information] : CZWave is running
20:55:03 : mainThread : [Error] : The ZWave plugin fails. exception : boost::too_few_args: format-string referred to more arguments than were passed
20:55:03 : mainThread : [Information] : Ending ZWave plugin
20:55:03 : ZWave : [Information] : OpenZWave notification : DriverRemoved
20:55:05 : ZWave : [Error] : ZWave has stopped itself.
20:55:05 : ZWave : [Information] : ZWave is stopped
20:55:06 : ZWave : [Information] : Close message queues

**Comment by jmberhault** [comment]
I will check if this case appears after a reset command, so the port would have changed.

**Comment by jano42** [comment]
Can not reproduce.
Probably already fixed.

**Comment by jano42** [comment]
Not reproductible. Close issue
