### ISSUE TITLE
Plugin Zwave : resetting Zwave USB Stick

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#196]
![image](https://cloud.githubusercontent.com/assets/16737541/24075999/6933955c-0c27-11e7-83de-236bed7ca050.png)

After resetting the stick controller, the CPU load is 100% for the ZWave plugin : 

![image](https://cloud.githubusercontent.com/assets/16737541/24075998/597b8e76-0c27-11e7-9334-41849ece5b62.png)

After this step extra-commands doesn't works any more. The plugin stay "running". The only way is to stop the plugin, but drivers fails to restart : 

21:05:15 : mainThread : [Information] : Extra command received : softReset
21:05:28 : mainThread : [Information] : Extra command received : inclusionMode
21:05:28 : ZWave : [Information] : OpenZWave notification : ControllerComand - Starting
21:05:29 : ZWave : [Information] : OpenZWave notification : Notification - TimeOut
21:05:29 : ZWave : [Information] : OpenZWave notification : ControllerCommand - Error - Failed
21:05:29 : ZWave : [Error] : Command controller error : Failed
21:09:24 : mainThread : [Information] : Extra command received : exclusionMode
21:09:24 : ZWave : [Information] : OpenZWave notification : ControllerComand - Starting
21:09:25 : ZWave : [Information] : OpenZWave notification : Notification - TimeOut
21:09:25 : ZWave : [Information] : OpenZWave notification : ControllerCommand - Error - Failed
21:09:25 : ZWave : [Error] : Command controller error : Failed
21:09:31 : mainThread : [Information] : Stop requested
21:09:31 : mainThread : [Information] : Ending ZWave plugin
21:09:31 : ZWave : [Information] : OpenZWave notification : DriverRemoved
21:09:33 : ZWave : [Information] : ZWave is stopped
21:09:33 : ZWave : [Information] : Close message queues
21:09:59 : mainThread : [Information] : ZWave started
21:09:59 : mainThread : [Information] : CZWave is initializing
21:10:19 : ZWave : [Information] : OpenZWave notification : DriverFailed
21:10:19 : mainThread : [Error] : Fail to initialize controller
21:10:19 : mainThread : [Error] : Cannot start ZWave controller. Plugin ends.
21:10:19 : mainThread : [Information] : Ending ZWave plugin
21:10:19 : ZWave : [Information] : OpenZWave notification : DriverRemoved
21:10:19 : ZWave : [Error] : ZWave has stopped itself.
21:10:19 : ZWave : [Information] : ZWave is stopped
21:10:20 : ZWave : [Information] : Close message queues

**Comment by jmberhault** [comment]
This issue looks to be linked to the issue #105.

**Comment by jmberhault** [comment]
After resetting the ZWave USB Stick, should we stop the plugin ? The stick port looks to change, so the configuration into the plugin is not correct. I think this why, we have a so high CPU load. If I stop and restart the plugin, it restart with the good port (perhaps, it's some luck ... But it works).

**Comment by jmberhault** [comment]
This issue about cpu load could be linked to the #297. I will test.

**Comment by jmberhault** [comment]
This issue is linked to the #267. We cannot reset the Zwave USB Dongle.

**Comment by jano42** [comment]
This issue should be just fixed by better message to user
=> #323
