### ISSUE TITLE
Plugin ZWave : exit exclusion mode when precedent command failed

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#197]
21:11:11 : mainThread : [Information] : ZWave started
21:11:12 : mainThread : [Information] : CZWave is initializing
21:11:12 : ZWave : [Information] : OpenZWave notification : DriverReady
21:11:12 : ZWave : [Information] : OpenZWave notification : NodeAdded
21:11:12 : ZWave : [Information] : OpenZWave notification : NodeProtocolInfo
21:11:12 : ZWave : [Information] : ZWave : NodeProtocolInfo : Static PC Controller
21:11:12 : ZWave : [Information] : OpenZWave notification : EssentialNodeQueriesComplete
21:11:12 : ZWave : [Information] : OpenZWave notification : ValueAdded
21:11:12 : ZWave : [Information] : OpenZWave notification : NodeNaming
21:11:12 : ZWave : [Information] : ZWave : NodeNaming : id = 3701551950.1
21:11:12 : ZWave : [Information] : ZWave : NodeNaming : name = 
21:11:12 : ZWave : [Information] : ZWave : NodeNaming : manufacturer = Aeotec
21:11:12 : ZWave : [Information] : ZWave : NodeNaming : productName = Z-Stick Gen5
21:11:12 : ZWave : [Information] : ZWave : NodeNaming : productType = 0x0001
21:11:12 : ZWave : [Information] : ZWave : NodeNaming : productId = 0x005a
21:11:12 : ZWave : [Information] : OpenZWave notification : NodeQueriesComplete
21:11:12 : ZWave : [Information] : OpenZWave notification : AllNodesQueried
21:11:12 : ZWave : [Information] : OpenZWave notification : NodeQueriesComplete
21:11:12 : mainThread : [Information] : CZWave is running
21:11:25 : mainThread : [Information] : Extra command received : cancelCommand
21:11:25 : mainThread : [Error] : Fail to cancel last command
21:11:52 : mainThread : [Information] : Extra command received : inclusionMode
21:11:52 : ZWave : [Information] : OpenZWave notification : ControllerComand - Starting
21:11:52 : ZWave : [Information] : OpenZWave notification : ControllerCommand - Waiting
21:13:43 : mainThread : [Information] : Extra command received : cancelCommand
21:13:43 : ZWave : [Information] : OpenZWave notification : ControllerCommand - Canceled
21:13:43 : ZWave : [Information] : OpenZWave notification : ControllerCommand - Completed
21:13:56 : mainThread : [Information] : Extra command received : exclusionMode
21:13:56 : ZWave : [Information] : OpenZWave notification : ControllerComand - Starting
21:13:56 : ZWave : [Information] : OpenZWave notification : ControllerCommand - Waiting
21:14:02 : mainThread : [Information] : Extra command received : cancelCommand
21:14:02 : ZWave : [Information] : OpenZWave notification : ControllerCommand - Canceled
21:14:09 : mainThread : [Information] : Extra command received : exclusionMode
21:14:09 : ZWave : [Information] : OpenZWave notification : ControllerComand - Starting
21:14:09 : ZWave : [Information] : OpenZWave notification : ControllerCommand - Waiting
21:14:16 : ZWave : [Information] : OpenZWave notification : ControllerCommand - InProgress
21:14:17 : ZWave : [Information] : OpenZWave notification : ControllerCommand - Failed
21:14:45 : mainThread : [Information] : Extra command received : cancelCommand
21:14:45 : mainThread : [Error] : Fail to cancel last command

When a command failed in exclusion mode, I cannot exit from the exclusion mode (cancel last command doesn't work), so I'm stuck to this state. The only way is to restart the plugin.

**Comment by jano42** [comment]
This is probably an issue due to OpenZWave.
Since it has been updated many times since opening this issue, we need to check issue validity again
