### ISSUE TITLE
Plugin ZWave : Cancel inclusion mode with no nodes in the network

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#198]
When the USB Stick is not configured, when I start, the plugin, the plugin have the state driver Ready.

21:30:48 : mainThread : [Information] : ZWave started
21:30:48 : mainThread : [Information] : CZWave is initializing
21:30:48 : ZWave : [Information] : OpenZWave notification : DriverReady
21:30:48 : ZWave : [Information] : OpenZWave notification : NodeAdded
21:30:48 : ZWave : [Information] : OpenZWave notification : NodeProtocolInfo
21:30:48 : ZWave : [Information] : ZWave : NodeProtocolInfo : Static PC Controller
21:30:48 : ZWave : [Information] : OpenZWave notification : EssentialNodeQueriesComplete
21:30:48 : ZWave : [Information] : OpenZWave notification : ValueAdded
21:30:48 : ZWave : [Information] : OpenZWave notification : NodeNaming
21:30:48 : ZWave : [Information] : ZWave : NodeNaming : id = 3701551950.1
21:30:48 : ZWave : [Information] : ZWave : NodeNaming : name = 
21:30:48 : ZWave : [Information] : ZWave : NodeNaming : manufacturer = Aeotec
21:30:48 : ZWave : [Information] : ZWave : NodeNaming : productName = Z-Stick Gen5
21:30:48 : ZWave : [Information] : ZWave : NodeNaming : productType = 0x0001
21:30:48 : ZWave : [Information] : ZWave : NodeNaming : productId = 0x005a
21:30:48 : ZWave : [Information] : OpenZWave notification : NodeQueriesComplete
21:30:48 : ZWave : [Information] : OpenZWave notification : AllNodesQueried
21:30:49 : ZWave : [Information] : OpenZWave notification : NodeQueriesComplete

Now, I go to the inclusion mode, and I cancel the last command without adding any nodes, through extra commands, the plugin go to running state ... Logically, it should come back to driver ready.

21:32:55 : ZWave : [Information] : Extra command received : inclusionMode
21:32:55 : ZWave : [Information] : OpenZWave notification : ControllerComand - Starting
21:32:55 : ZWave : [Information] : OpenZWave notification : ControllerCommand - Waiting
21:33:58 : ZWave : [Information] : Extra command received : cancelCommand
21:33:58 : ZWave : [Information] : OpenZWave notification : ControllerCommand - Canceled
21:33:59 : ZWave : [Information] : OpenZWave notification : ControllerCommand - Completed

**Comment by jano42** [comment]
Probably fixed in branch 2_0_0.
