### ISSUE TITLE
Plugin Zwave : After reboot, plugin in "driver ready", and not "running" state

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#199]
After a reboot, the plugin is in "driver ready" state : 

17:25:06 : mainThread : [Information] : ZWave started
17:25:07 : mainThread : [Information] : CZWave is initializing
17:25:07 : ZWave : [Information] : OpenZWave notification : DriverReady
17:25:07 : ZWave : [Information] : OpenZWave notification : NodeAdded
17:25:07 : ZWave : [Information] : OpenZWave notification : NodeProtocolInfo
17:25:07 : ZWave : [Information] : ZWave : NodeProtocolInfo : Static PC Controller
17:25:07 : ZWave : [Information] : OpenZWave notification : EssentialNodeQueriesComplete
17:25:07 : ZWave : [Information] : OpenZWave notification : ValueAdded
17:25:07 : ZWave : [Information] : OpenZWave notification : NodeNaming
17:25:07 : ZWave : [Information] : ZWave : NodeNaming : id = 3334823588.1
17:25:07 : ZWave : [Information] : ZWave : NodeNaming : name = 
17:25:07 : ZWave : [Information] : ZWave : NodeNaming : manufacturer = Aeotec
17:25:07 : ZWave : [Information] : ZWave : NodeNaming : productName = Z-Stick Gen5
17:25:07 : ZWave : [Information] : ZWave : NodeNaming : productType = 0x0001
17:25:07 : ZWave : [Information] : ZWave : NodeNaming : productId = 0x005a
17:25:07 : ZWave : [Information] : OpenZWave notification : NodeAdded
17:25:07 : ZWave : [Information] : OpenZWave notification : NodeProtocolInfo
17:25:07 : ZWave : [Information] : ZWave : NodeProtocolInfo : General Thermostat V2
17:25:07 : ZWave : [Information] : OpenZWave notification : EssentialNodeQueriesComplete
17:25:07 : ZWave : [Information] : OpenZWave notification : ValueAdded
17:25:07 : ZWave : [Information] : [3334823588.] Temperature:SensorMultilevel [Genre=User] [CommandClass=49] [Instance=1] [ReadOnly=1] [WriteOnly= 0] [Polled= 0] [Set= 0] [Units= C] [Awake= 1] [Failed= 0] [ZWave+= 0]
17:25:07 : ZWave : [Information] : OpenZWave notification : ValueAdded
17:25:07 : ZWave : [Information] : [3334823588.] Mode:ThermostatMode [Genre=User] [CommandClass=64] [Instance=1] [ReadOnly=0] [WriteOnly= 0] [Polled= 0] [Set= 0] [Units= data.units.noUnit] [Awake= 1] [Failed= 0] [ZWave+= 0]
17:25:07 : ZWave : [Information] : {"name":"Mode","description":"","values":{"1":"Heat"}}

17:25:07 : ZWave : [Information] : {"name":"Mode","description":"","values":{"1":"Heat"}}

17:25:07 : ZWave : [Information] : OpenZWave notification : ValueAdded
17:25:07 : ZWave : [Information] : [3334823588.] Operating State:ThermostatOperatingState [Genre=User] [CommandClass=66] [Instance=1] [ReadOnly=1] [WriteOnly= 0] [Polled= 0] [Set= 0] [Units= data.units.noUnit] [Awake= 1] [Failed= 0] [ZWave+= 0]
17:25:07 : ZWave : [Information] : OpenZWave notification : ValueAdded
17:25:07 : ZWave : [Information] : [3334823588.] Heating 1:ThermostatSetpoint [Genre=User] [CommandClass=67] [Instance=1] [ReadOnly=0] [WriteOnly= 0] [Polled= 0] [Set= 0] [Units= C] [Awake= 1] [Failed= 0] [ZWave+= 0]
17:25:07 : ZWave : [Information] : {"name":"Heating 1","description":"","unit":"C","min":"0","max":"0","step":"1"}

17:25:07 : ZWave : [Information] : OpenZWave notification : ValueAdded
17:25:07 : ZWave : [Information] : [3334823588.] Temperature sensor reading:Configuration [Genre=Config] [CommandClass=112] [Instance=1] [ReadOnly=0] [WriteOnly= 0] [Polled= 0] [Set= 0] [Units= data.units.noUnit] [Awake= 1] [Failed= 0] [ZWave+= 0]
17:25:07 : ZWave : [Information] : {"name":"Temperature sensor reading","description":"Enables or not the temperature sensor reading","values":{"0":"Disabled","255":"Enabled"}}

17:25:07 : ZWave : [Information] : {"name":"Temperature sensor reading","description":"Enables or not the temperature sensor reading","values":{"0":"Disabled","255":"Enabled"}}

17:25:07 : ZWave : [Information] : OpenZWave notification : ValueAdded
17:25:07 : ZWave : [Information] : [3334823588.] Temperature Scale:Configuration [Genre=Config] [CommandClass=112] [Instance=1] [ReadOnly=0] [WriteOnly= 0] [Polled= 0] [Set= 0] [Units= data.units.noUnit] [Awake= 1] [Failed= 0] [ZWave+= 0]
17:25:07 : ZWave : [Information] : {"name":"Temperature Scale","description":"Controls the temperature sensor scale","values":{"0":"Celsius","255":"Fahrenheit"}}

17:25:07 : ZWave : [Information] : {"name":"Temperature Scale","description":"Controls the temperature sensor scale","values":{"0":"Celsius","255":"Fahrenheit"}}

17:25:07 : ZWave : [Information] : OpenZWave notification : ValueAdded
17:25:07 : ZWave : [Information] : [3334823588.] Delta T: Temperature change:Configuration [Genre=Config] [CommandClass=112] [Instance=1] [ReadOnly=0] [WriteOnly= 0] [Polled= 0] [Set= 0] [Units= data.units.noUnit] [Awake= 1] [Failed= 0] [ZWave+= 0]
17:25:07 : ZWave : [Information] : {"name":"Delta T: Temperature change","description":"Change between temperatures to trigger a temperature report (step 0.1) (Default 10 = 1C)","unit":"","min":"1","max":"100","step":"1"}

17:25:07 : ZWave : [Information] : {"name":"Delta T: Temperature change","description":"Change between temperatures to trigger a temperature report (step 0.1) (Default 10 = 1C)","unit":"","min":"1","max":"100","step":"1"}

17:25:07 : ZWave : [Information] : OpenZWave notification : ValueAdded
17:25:07 : ZWave : [Information] : [3334823588.] Battery Level:Battery [Genre=User] [CommandClass=128] [Instance=1] [ReadOnly=1] [WriteOnly= 0] [Polled= 0] [Set= 0] [Units= %] [Awake= 1] [Failed= 0] [ZWave+= 0]
17:25:07 : ZWave : [Information] : {"name":"Battery Level","description":"","unit":"%","min":"0","max":"255","step":"1"}

17:25:07 : ZWave : [Information] : {"name":"Battery Level","description":"","unit":"%","min":"0","max":"255","step":"1"}

17:25:08 : ZWave : [Information] : OpenZWave notification : ValueAdded
17:25:08 : ZWave : [Information] : OpenZWave notification : ValueAdded
17:25:08 : ZWave : [Information] : OpenZWave notification : ValueAdded
17:25:08 : ZWave : [Information] : OpenZWave notification : ValueAdded
17:25:08 : ZWave : [Information] : OpenZWave notification : ValueAdded
17:25:08 : ZWave : [Information] : OpenZWave notification : Group
17:25:08 : ZWave : [Debug] : Group change : id=  label=Lifeline
17:25:08 : ZWave : [Information] : OpenZWave notification : Group
17:25:08 : ZWave : [Debug] : Group change : id=  label=Thermostat Operating State Reports
17:25:08 : ZWave : [Information] : OpenZWave notification : Group
17:25:08 : ZWave : [Debug] : Group change : id=  label=Unsolicited Battery Level Reports
17:25:08 : ZWave : [Information] : OpenZWave notification : Group
17:25:08 : ZWave : [Debug] : Group change : id=  label=Thermostat Set Point Reports
17:25:08 : ZWave : [Information] : OpenZWave notification : Group
17:25:08 : ZWave : [Debug] : Group change : id=  label=Unsolicited Sensor Multilevel Reports
17:25:08 : ZWave : [Information] : OpenZWave notification : ValueAdded
17:25:08 : ZWave : [Information] : OpenZWave notification : ValueAdded
17:25:08 : ZWave : [Information] : OpenZWave notification : ValueAdded
17:25:08 : ZWave : [Information] : OpenZWave notification : NodeNaming
17:25:08 : ZWave : [Information] : ZWave : NodeNaming : id = 3334823588.2
17:25:08 : ZWave : [Information] : ZWave : NodeNaming : name = 
17:25:08 : ZWave : [Information] : ZWave : NodeNaming : manufacturer = Horstmann
17:25:08 : ZWave : [Information] : ZWave : NodeNaming : productName = SRT 323 Electronic Room Thermostat and Temperature
17:25:08 : ZWave : [Information] : ZWave : NodeNaming : productType = 0x0001
17:25:08 : ZWave : [Information] : ZWave : NodeNaming : productId = 0x0004
17:25:12 : ZWave : [Information] : OpenZWave notification : Notification - NoOperation
17:25:12 : ZWave : [Information] : OpenZWave notification : Notification - Node Asleep
17:25:12 : ZWave : [Information] : OpenZWave notification : NodeQueriesComplete
17:25:12 : ZWave : [Information] : OpenZWave notification : AwakeNodesQueried
17:25:12 : mainThread : [Information] : CZWave is running
17:25:12 : ZWave : [Information] : OpenZWave notification : NodeQueriesComplete

![image](https://cloud.githubusercontent.com/assets/16737541/24113028/ae39d66e-0d9b-11e7-9729-12a2d4d1f6fd.png)

**Comment by jano42** [comment]
Change to minor level, because this not affect plugins but just the displayed state.

**Comment by jmberhault** [comment]
closed in branch 2_0_0
