### ISSUE TITLE
GUI : Installation & Update

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#204]
Some errors with script Interpreter

![image](https://cloud.githubusercontent.com/assets/16737541/24136762/9dc0dcb8-0e10-11e7-9166-39bdf3644c8f.png)

**Comment by sgallou** [comment]
It seems that it's a confusion in the key "name" or "type" in package.json. Plugins are using "type", script interpreters are using "name". But dashboard expect sometimes "type" and sometimes "name" for script interpreters.
I suggest to use "type" every where.

**Comment by jano42** [comment]
This seems to be a developer mode effect.

When the developer mode is enabled, then the install/update use an altenrative package repository for validation purpose. This alternative repository contains invalid package.jon, invalid zip,... to make sure GUI runs with some bad server data

**Comment by jano42** [comment]
Change to enhancement, we need to display a message when dev mode is enabled for page install/update

**Comment by jano42** [comment]
The confusion "name"/"type" is not to take into account here. Because server data are voluntarily done

**Comment by jano42** [comment]
Fixed in 2_0_0-rc_1
