### ISSUE TITLE
GUI : configuration buttons not well positionned on phones

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#205]
See this screenshot :

![screenshot_20170322-144942](https://cloud.githubusercontent.com/assets/6855339/24201300/f156f556-0f0f-11e7-9c60-9b829b82f172.png)

**Comment by jano42** [comment]
Not a bug.
This is the recommended display of menu items

**Comment by sgallou** [comment]
Sounds strange because behavior is different from web navigation under desktop computer...

**Comment by jano42** [comment]
I've got exactly the same behavior.
On small screens the menus are pull left

![image](https://cloud.githubusercontent.com/assets/3135683/24202344/1031a8a6-0f13-11e7-9388-93e03d678f3f.png)
