### ISSUE TITLE
Add a title to email messages

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#218]
Add the possibility to change the title for an email. At this time, an e-mail has the title : "Yadoms Notification !". It could be great to customize it for example with a type of notification : "temperature threshold, fire alarm, ...".

![image](https://cloud.githubusercontent.com/assets/16737541/24840559/48379ac0-1d6f-11e7-95cb-e2f4f3f5fe15.png)

**Comment by jano42** [comment]
The "notify" block allow only to send "simple text" notification. It is not depending on the sender used. It can be email, sms,.... All available senders for this block implements "simple message text".

I think we should have another block for sending more complex messages.

**Comment by jmberhault** [comment]
Yes, I think so. for me, 2 types of messaging : 
- notification with only message text.
- message with a subject, and a text object and perhaps more, with joined pieces (example: images sent from a webcam plugin, ...).

**Comment by sgallou** [comment]
Not an issue
