### ISSUE TITLE
Blockly : time in log scripts doesn't work

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#221]
21:37:58 : [Information] : Every minutes
21:37:58 : [Information] : Reception of a data every 30s
21:37:58 : [Information] : Reception of a data every 30s
21:37:58 : [Information] : Every minutes
21:37:58 : [Information] : Reception of a data every 30s
21:37:58 : [Information] : Reception of a data every 30s
21:37:58 : [Information] : Every minutes
21:37:58 : [Information] : Reception of a data every 30s
21:37:58 : [Information] : Reception of a data every 30s
21:37:58 : [Information] : Every minutes
21:37:58 : [Information] : Reception of a data every 30s

Always the same time : v2.0.0-rc.2 for windows

**Comment by sgallou** [comment]
Fix in branch 2_0_0
