### ISSUE TITLE
[Blockly] Set keyword can access to message (but fails)

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#225]
It should not be possible to drive a "message" keyword with writeKeyword block :

![image](https://cloud.githubusercontent.com/assets/6855339/25046454/c8a465ec-2131-11e7-9bfa-203e238418f4.png)

Doing that make MailSender plugin fail because value sent to plugin is a simple string "Hello", instead of JSON tree with the 2 fields "to" and "body".

**Comment by jano42** [comment]
Fixed in branch 2_0_0.

**Comment by sgallou** [comment]
Can not send notification anymore (tried with email or FreeMobileSms). Blockly "notification" block don't list devices and keyword (plugins are well instanciated, and recipients are well configured) :

![image](https://cloud.githubusercontent.com/assets/6855339/25918178/cc5680dc-35ca-11e7-8005-ac61614b6206.png)
