### ISSUE TITLE
RFXCOM : RFY device

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#226]
RFY devices don't have the device configuration as RFXManager.

![configuration somfy](https://cloud.githubusercontent.com/assets/16737541/25093775/0d154f84-2394-11e7-8f51-07460a29940d.png)

![image](https://cloud.githubusercontent.com/assets/16737541/25093790/1938fefa-2394-11e7-80b6-29db8007d4aa.png)

**Comment by sgallou** [comment]
No mean to represent hexa number is available in configuration for now.
It's not an issue but en enhancement.
