### ISSUE TITLE
Inscription forum

### ISSUE THREAD

**Issue by lielmime** [Yadoms/yadoms#228]
Bonjour,

Je découvre votre application domotique.
Agréablement surpris de la facilité de l'installation (version binaire Raspberry Pi) et des plugins disponibles.

Concernant le forum, je me trompe peut-être mais il dois manquer quelque chose pour le controle de sécurité:

    Contrôle de sécurité
    To use reCAPTCHA you must get an API key from https://www.google.com/recaptcha/admin/create

**Comment by jano42** [comment]
Bonjour

Merci pour votre message.

A quel moment avez-vous eu ce problème ? pour laisser un commentaire ? pour s'enregistrer ? 

Merci

**Comment by sgallou** [comment]
Bonjour, ça doit être corrigé. Effectivement, le captcha n'était pas activé.
Si vous pouvez nous confirmer que c'est bon pour vous,
merci

**Comment by sgallou** [comment]
Comme vous pouvez le constater, vous êtes le premier sur le forum, soyez le bienvenu ! :-)

**Comment by lielmime** [comment]
je confirme l'enregistrement avec le captcha fonctionne.

et merci pour l'accueil

**Comment by sgallou** [comment]
Merci !
