### ISSUE TITLE
[Blockly - Scripts] Miss events

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#234]
This simple script :
![image](https://cloud.githubusercontent.com/assets/6855339/25426416/55c65570-2a6f-11e7-86f8-a4bf5f3a0a0f.png)

make logs like :

> Wed, 09:07:25 : [Information] : #### START ####
> Wed, 09:07:25 : [Information] : Script started
> Wed, 09:07:25 : [Information] : 09:14:00
> Wed, 09:07:25 : [Information] : 09:18:00
> Wed, 09:07:25 : [Information] : 09:20:00
> Wed, 09:07:25 : [Information] : 09:22:00
> Wed, 09:07:25 : [Information] : 09:23:00
> Wed, 09:07:25 : [Information] : 09:26:00
> Wed, 09:07:25 : [Information] : 09:39:00
> Wed, 09:07:25 : [Information] : 09:51:00
> Wed, 09:07:25 : [Information] : 09:52:00
> Wed, 09:07:25 : [Information] : 10:31:00
> Wed, 09:07:25 : [Information] : 10:42:00

Every minutes should be logged

**Comment by jano42** [comment]
Can not reproduce. Tested with branch 2_0_0

**Comment by sgallou** [comment]
Can be closed for now but we have to keep in mind that this solution is not perfect, for the only case where a wait operation is done on every minute + an acquisition event. In this specific case (only), some 'minute' events can be lost when acquisition arrives just before the 'minute' event :

- 10:45:30 : a waitForEvent(keywordId3, everyMinute) is started. Next 'minute' event is at 10:46:00
- 10:45:59 ==> a keyword event is signaled on keywordId3
- 10:45:59 : process the event, can take several seconds
- 10:46:00 : process ended (was not so long !), restart the waitForEvent(keywordId3, everyMinute). The next 'minute' event will be at 10:47:00
==> We lost 'minute' event at 10:46:00

No mean to do better. If we stack all 'minute' events, we will experience issue is event process take more than 1 minute :
- 10:45:30 : a waitForEvent(everyMinute) is started. Next 'minute' event is at 10:46:00
- 10:46:00 ==> 'minute' event is signaled
- 10:46:00 : process the event, take more than 1 minute (ie 63 seconds)
- 10:47:03 : process ended, restart the waitForEvent(everyMinute). The next 'minute' event will be at 10:47:00
- 10:47:03 ==> 'minute' event is signaled (for 10:47:00)
- 10:47:03 : process the event, take more than 1 minute (still 63 seconds)
- 10:48:06 : process ended, restart the waitForEvent(everyMinute). The next 'minute' event will be at 10:48:00
==> Drift...
