### ISSUE TITLE
Plugin One Wire: Error writing IO Switch

### ISSUE THREAD

**Issue by lielmime** [Yadoms/yadoms#237]
Hi,
I'am on Raspberry-Pi 2 with yadoms-raspberrypi-2.0.0-rc.2

I have 1-wire chips like IO Switch:  DS2405

    $ l /mnt/1wire/05.3A9233000000/
    total 0
    -r--r--r-- 1 root root  16 avril 28 16:41 address
    -rw-rw-rw- 1 root root 256 avril 28 16:41 alias
    -r--r--r-- 1 root root   2 avril 28 16:41 crc8
    -r--r--r-- 1 root root   2 avril 28 16:41 family
    -r--r--r-- 1 root root  12 avril 28 16:41 id
    -r--r--r-- 1 root root  16 avril 28 16:41 locator
    -rw-rw-rw- 1 root root   1 avril 28 17:41 PIO
    -r--r--r-- 1 root root  16 avril 28 16:41 r_address
    -r--r--r-- 1 root root  12 avril 28 16:41 r_id
    -r--r--r-- 1 root root  16 avril 28 16:41 r_locator
    -r--r--r-- 1 root root   1 avril 28 17:41 sensed
    -r--r--r-- 1 root root  32 avril 28 16:41 type

I configure un widget Switch with this device:

![yadom_0002](https://cloud.githubusercontent.com/assets/27768412/25536262/6ea43752-2c3a-11e7-8f95-852858426af3.png)

When I use the widget to change the output state, I have this error:

    16:50:42 : Plugin.3 : [Information] : Command received :5-00000033923A.state=1
    16:50:42 : Plugin.3 : [Error] : 1-wire write : Error opening /mnt/1wire/uncached/05.3A9233000000/sensed/PIO

This should not be this file /mnt/1wire/uncached/05.3A9233000000/PIO for writing ?

**Comment by sgallou** [comment]
Yes you right, I will fix it ASAP.

**Comment by sgallou** [comment]
Fixed in 2_0_0 branch (but not yet tested)

**Comment by sgallou** [comment]
I don't have such device, so can not test. If I provide a version to you, can you test the fix for me, please ?
Thanks

**Comment by lielmime** [comment]
yes, 
no problem

**Comment by lielmime** [comment]
I tested to build on RaspberryPI the yadom source with this doc: https://github.com/Yadoms/yadoms/wiki/Build-on-RaspberryPI


The requested file **FindProtobuf.cmake** for CMake versions before 3.9  is not found:

    $ wget https://raw.githubusercontent.com/Kitware/CMake/next/Modules/FindProtobuf.cmake
    Résolution de raw.githubusercontent.com (raw.githubusercontent.com)… 151.101.120.133
    Connexion à raw.githubusercontent.com (raw.githubusercontent.com)|151.101.120.133|:443… connecté.
    requête HTTP transmise, en attente de la réponse… 404 Not Found
    2017-05-01 18:29:09 erreur 404 : Not Found.

I tested with these versions

     wget https://raw.githubusercontent.com/Kitware/CMake/master/Modules/FindProtobuf.cmake
     wget https://raw.githubusercontent.com/Kitware/CMake/release/Modules/FindProtobuf.cmake

But  have error when building Yadom makefile:

    $ sh cmake_raspberry.sh p      
    ### Building Yadoms 2.0.0-rc.3 ###
    
    -- Compiler = GNU
    -- Compiler Version = 4.9.2
    -- cotire 1.7.9 loaded.
    System Name = Linux
    -- Boost version: 1.62.0
    -- Found the following Boost libraries:
    --   atomic
    --   system
    --   filesystem
    --   thread
    --   date_time
    --   chrono
    --   regex
    -- Poco package version: 1.7.7
    -- Found the following Poco libraries:
    --   PocoUtil
    --   PocoNetSSL
    --   PocoCrypto
    --   PocoZip
    --   PocoXML
    --   PocoNet
    --   PocoJSON
    --   PocoFoundation
    CMake Error at /usr/local/share/cmake-3.7/Modules/FindProtobuf.cmake:357 (file):
      file STRINGS file
      "/usr/src/protobuf-3.2.0/include/google/protobuf/stubs/common.h" cannot be
      read.
    Call Stack (most recent call first):
      CMakeLists.txt:218 (find_package)
    
    
    CMake Error at /usr/local/share/cmake-3.7/Modules/FindProtobuf.cmake:363 (math):
      math cannot parse the expression: " / 1000000": syntax error, unexpected
      exp_DIVIDE, expecting exp_OPENPARENT or exp_NUMBER (2)
    Call Stack (most recent call first):
      CMakeLists.txt:218 (find_package)
    
    
    CMake Error at /usr/local/share/cmake-3.7/Modules/FindProtobuf.cmake:364 (math):
      math cannot parse the expression: " / 1000 % 1000": syntax error,
      unexpected exp_DIVIDE, expecting exp_OPENPARENT or exp_NUMBER (2)
    Call Stack (most recent call first):
      CMakeLists.txt:218 (find_package)
    
    
    CMake Error at /usr/local/share/cmake-3.7/Modules/FindProtobuf.cmake:365 (math):
      math cannot parse the expression: " % 1000": syntax error, unexpected
      exp_MOD, expecting exp_OPENPARENT or exp_NUMBER (2)
    Call Stack (most recent call first):
      CMakeLists.txt:218 (find_package)
    
    
    CMake Error at /usr/local/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
      Could NOT find Protobuf: Found unsuitable version "..", but required is at
      least "3.0.0" (found /usr/src/protobuf-3.2.0/lib/libprotobuf.a;-lpthread)
    Call Stack (most recent call first):
      /usr/local/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
      /usr/local/share/cmake-3.7/Modules/FindProtobuf.cmake:393 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
      CMakeLists.txt:218 (find_package)
    
    
    -- Configuring incomplete, errors occurred!

**Comment by sgallou** [comment]
It seems that Kitware removed the file. Maybe you can try with this one.
[FindProtobuf.zip](https://github.com/Yadoms/yadoms/files/968467/FindProtobuf.zip)

But you have to know that building on a Raspberry is maybe not full functional. We don't build anymore directly on Pi because of memory limitations and performances. We apologize for the wiki that is not up-to-date (I will update it soon).
Now, we [cross-compile](https://github.com/Yadoms/yadoms/wiki/Cross-compile-for-raspberry-PI) the project for Pi target under Linux (Ubuntu).

**Comment by lielmime** [comment]
I tested writing on the 1-wire chip with yadom version you sent me and it's works
thank
