### ISSUE TITLE
Widget Counter Display : Display only weather pressure device as choice

### ISSUE THREAD

**Issue by lielmime** [Yadoms/yadoms#238]
On yadoms-raspberrypi-2.0.0-rc.2

With this Widget:
![yadom_0004](https://cloud.githubusercontent.com/assets/27768412/25536669/e06cf8e6-2c3b-11e7-9f93-254917665edb.png)

I can only choose the weather/pressure equipement:

![yadom_0003](https://cloud.githubusercontent.com/assets/27768412/25536649/d6575d10-2c3b-11e7-9c40-37d2e89a2f67.png)

But I have some Onewire counter:

![yadom_0005](https://cloud.githubusercontent.com/assets/27768412/25536808/56fce674-2c3c-11e7-9a68-cbea534b0d49.png)

**Comment by sgallou** [comment]
@jmberhault : FYI, DS2423 historize a yApi::historization::CCounter keyword (Cumulative). Need to fix the counter accepted capacities.

**Comment by jmberhault** [comment]
fixed in branch 2_0_0 with commit f2fecee.

**Comment by lielmime** [comment]
I tested with yadom version you sent me and I can set this witget to 1-wire counter
thank
