### ISSUE TITLE
Plugin One Wire: Log file

### ISSUE THREAD

**Issue by lielmime** [Yadoms/yadoms#239]
Possible to enable more debug on log ?

I only have that for this plugin:

    # Log file created/rotated Friday, 28 Apr 17 14:11:43 GMT
    16:11:43 : mainThread : [Information] : OneWire is stopped
    16:11:43 : mainThread : [Information] : Close message queues
    16:40:00 : mainThread : [Information] : OneWire started
    16:40:34 : mainThread : [Information] : OneWire is stopped
    16:40:34 : mainThread : [Information] : Close message queues
    16:48:43 : mainThread : [Information] : OneWire started

yadoms-raspberrypi-2.0.0-rc.2

**Comment by sgallou** [comment]
In yadoms.ini file, you can set up log level. Set it to 'trace' to have the most logs (yadoms.ini file is self-documented). More information about [yadoms.ini](https://github.com/Yadoms/yadoms/wiki/How-to-run-Yadoms) file.
But OneWire is a bit special to set-up, as it requires some OS configuration, depending on the hardware you use. [Documentation is here](https://github.com/Yadoms/yadoms/wiki/OneWire).

Please let me know if it solves your issue.

**Comment by lielmime** [comment]
I have tested with debug and trace in yadoms.ini, 
there are more logs in yadoms.log but OneWire not more verbose:

    20:19:07 : mainThread : [Information] : OneWire started
    20:57:11 : mainThread : [Information] : OneWire is stopped
    20:57:11 : mainThread : [Information] : Close message queues
    20:58:24 : mainThread : [Information] : OneWire started
    21:17:29 : mainThread : [Information] : OneWire is stopped
    21:17:29 : mainThread : [Information] : Close message queues
    21:18:06 : mainThread : [Information] : OneWire started

It does not matter, it was just to check the plugin, I can see the "[Error]" in yadoms.log.

thanks

**Comment by sgallou** [comment]
Ok, this plugin still have our old log system (with only 2 log levels), writing to standard output (that is redirected to yadoms.log).
I will fix it to use new log system.

**Comment by sgallou** [comment]
Fixed by 510d4486f2d11ed8b44b1b37ee9d8c7df7416a07
