### ISSUE TITLE
[Shutter widget] Inverse state

### ISSUE THREAD

**Issue by lielmime** [Yadoms/yadoms#242]
The inverse state in Widget configuration does not seem to work.

![yadom_0001](https://cloud.githubusercontent.com/assets/27768412/25585370/74173380-2e9a-11e7-8d42-6cd2e5df3f7a.png)

Selected or not, the Widget alway display a "closed door" for a "1" value (plugin onewire)
Same problem with a rfxcom equipement (on/off value).

**Comment by jmberhault** [comment]
We notice a problem when we change the tab of Yadoms. We change the tab, and when we returned, the value of the widget changed, it's a real issue, I will fix it tomorrow.

The reverse state looks to work.

**Comment by jmberhault** [comment]
fixed in branch 2_0_0.

**Comment by jmberhault** [comment]
present in 2_0_0.rc4.
