### ISSUE TITLE
Raspberry build - segmentation fault

### ISSUE THREAD

**Issue by klorydryk** [Yadoms/yadoms#244]
Hi,
I tried to build and deploy Yadoms on my Raspberry, following this Howto: **https://github.com/Yadoms/yadoms/wiki/Build-on-RaspberryPI**
Unfortunately, after 2 days deploying and compiling all this tools, the Yadosm build crashed with this error :
```
cmake --build projects
[...]
Scanning dependencies of target yadoms-shared
[  0%] Building CXX object shared/CMakeFiles/yadoms-shared.dir/stdafx.cpp.o

g++-4.9: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
shared/CMakeFiles/yadoms-shared.dir/build.make:77: recipe for target 'shared/CMakeFiles/yadoms-shared.dir/stdafx.cpp.o' failed
make[2]: *** [shared/CMakeFiles/yadoms-shared.dir/stdafx.cpp.o] Error 4
CMakeFiles/Makefile2:272: recipe for target 'shared/CMakeFiles/yadoms-shared.dir/all' failed
make[1]: *** [shared/CMakeFiles/yadoms-shared.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

```

Any idea of what could be wrong? The libs versions I used:
openssl-1.1.0e
poco-1.7.8p2-all
protobuf-cpp-3.3.0
swig-3.0.12.tar.gz
boost_1_64_0
cmake-3.8.0

Thanks.

**Comment by sgallou** [comment]
Hi klorydryk, and thanks for your interest on Yadoms.

Unfortunately, your issue can depend on a lot of things. All what I can suggest you is to check that all libraries are built with the -fPIC c++ flag.

You also have to know that Raspberry PI 1 have no enough memory to build Yadoms (I don't know which Raspberry version you use).

I also suggest you to cross-compile from linux machine (we are doing so on Ubuntu), it's much faster, even on a virtual machine.
For your information, we use these libraries versions (sorry, the wiki is maybe not up-to-date) :
* CMake 3.7.2
* Boost 1.63.0
* Openssl 1.0.2k
* Poco 1.7.8-all
* Protobuf 3.2.0
* Swig 3.0.12

Last thing : our official build for Raspberry is in a separate [repository](https://github.com/Yadoms/yadoms-build_raspberrypi) and use Travis, so you can check the .travis.yml file to see build steps. We are sure that this method works !

Hope you will solve your issue,
sgallou

**Comment by klorydryk** [comment]
I tried to make the RP image, under Manjaro... and it is not working.
Using Debian, you should add ZIP in the dependancies list: stopping just before the end because of missing zip is a shame ;)
I have in the end an error message with the RSYNC command "no space left on device". This is a virtual machine, and I start with 20Go free. It isn't enough?

Thanks.

**Comment by sgallou** [comment]
Yes, we have now a downloadable Raspberry image, since yesterday ;-)
See [here](yadoms.com/download.html). 

20 Go may be not enough when you have to build all dependencies. I experimented same issue under Ubuntu.

I don't know Debian distro, but as far as I understand, [zip package seems installed](https://packages.debian.org/fr/wheezy/zip) (depending on versions).

**Comment by klorydryk** [comment]
The url is not correct (404). Direct address for Pi img 2.0.0-rc2 is https://github.com/Yadoms/yadoms/releases/download/2.0.0-rc.2/Yadoms-2.0.0-rc.2-RaspberryPI.img.zip
I'll try it. Thanks!

**Comment by sgallou** [comment]
You right !
I Fixed my post.

**Comment by klorydryk** [comment]
It is working, and I'm trying it. Do I continue the discussion here?
Like the "Installation & updates" giving the following error:
Erreur lors du téléchargement de scriptInterpreters/[object Object]/package.json

**Comment by sgallou** [comment]
No, please open a new issue
