### ISSUE TITLE
[Dashboard devices] Update device data after device configuration

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#245]
Device configuration can modify the keywords list, so all device data must be refreshed after changing the device configuration.
In case of 1Wire DS2438 device, new keyword can be created depending on the sensor connected to VAD input. In such case, the keyword list is not refresh and new keyword does not appear until a clic on "devices" tab.

**Comment by jmberhault** [comment]
Fixed in branch 2_0_0.
