### ISSUE TITLE
Raspberry img: "Installation & updates" tab error

### ISSUE THREAD

**Issue by klorydryk** [Yadoms/yadoms#246]
I just installed the recent Raspberry image of the 2.0.0 rc2 version of Yasdoms. When I open the "Installation & updates" tab, it gives me the following error:
Erreur lors du téléchargement de scriptInterpreters/[object Object]/package.json
Some parameter to update?
Thanks.

**Comment by jmberhault** [comment]
I could reproduce the same error with browser logs : 

![image](https://cloud.githubusercontent.com/assets/16737541/25774640/f2243096-3293-11e7-846c-80423603cc57.png)

**Comment by klorydryk** [comment]
Before to be able to get back this feature, how works the manual update?

**Comment by sgallou** [comment]
Backup your database (yadoms.db3) and your scripts folder (from /opt/yadoms).
Then untar the tar.bz2 content into opt/yadoms folder and copy back your database and scripts.

**Comment by klorydryk** [comment]
Ok, update done successfully.
Got this "waitForEventResult" error -> back to RC2 :)

**Comment by sgallou** [comment]
Yes, sorry... It seems that RC4 will come soon...

**Comment by jano42** [comment]
Errors fixed in branch 2_0_0
