### ISSUE TITLE
Raspberry img: installing ZWave plugin failed

### ISSUE THREAD

**Issue by klorydryk** [Yadoms/yadoms#247]
I just installed the recent Raspberry image of the 2.0.0 rc2 version of Yasdoms. After installing the ZWave plugin, I configure it, but selecting both ttyAMA0 or ttyUSB0 don't work.
The DMESG informations:
`dmesg | grep tty
[    0.000000] Kernel command line: bcm2708_fb.fbwidth=656 bcm2708_fb.fbheight=416 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x1ec00000 vc_mem.mem_size=0x20000000  dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
[    0.001399] console [tty1] enabled
[    1.057534] 20201000.serial: ttyAMA0 at MMIO 0x20201000 (irq = 81, base_baud = 0) is a PL011 rev2
[    1.894588] console [ttyAMA0] enabled
[    3.795545] systemd[1]: Expecting device dev-ttyAMA0.device...
[    7.474399] usb 1-1.3: cp210x converter now attached to ttyUSB0`

And the logs:
`17:33:48 : Plugin.3 : [Information] : 2017-05-06 17:33:48.650 Error, ERROR: Cannot open serial port /dev/ttyAMA0. Error code 13
17:33:48 : Plugin.3 : [Information] : 2017-05-06 17:33:48.652 Error, ERROR: Failed to open serial port /dev/ttyAMA0
`
`17:34:37 : Plugin.3 : [Information] : 2017-05-06 17:34:37.333 Error, ERROR: Cannot open serial port /dev/ttyUSB0. Error code 13
17:34:37 : Plugin.3 : [Information] : 2017-05-06 17:34:37.335 Error, ERROR: Failed to open serial port /dev/ttyUSB0
`

What should I do to help it recognize my ZWave USB stick aeonLabs?

**Comment by sgallou** [comment]
It seems that you have rights issue. See [this post](https://groups.google.com/forum/#!topic/openzwave/qG9y2ODkGCc).

Add 'pi' user to /etc/group file in dialout.

It seems that I need to add this in the Raspberry Pi SD card image...

**Comment by klorydryk** [comment]
`sudo groupadd dialout`
And it starts! Thanks.
