### ISSUE TITLE
"Automation center" can't save any rule

### ISSUE THREAD

**Issue by klorydryk** [Yadoms/yadoms#249]
My installation is based on the Raspberry image of the 2.0.0 rc2 version of Yasdoms.

I try to create a rule in the "automation center".
- Code is not available ("can't edit rule")
- Blockly allow to create a rule, but when I try to save it as test (or whatever), I get this error: "Impossible to create rule "test"".

**Comment by sgallou** [comment]
Sorry, it seems that image was not enough tested...
I will look at that ASAP.

**Comment by sgallou** [comment]
Please try to install python (seems to be not installed by default) :
sudo apt-get install python

**Comment by klorydryk** [comment]
Indeed, it wasn't installed by default. Same errors, before to reboot (is there any service to restart instead of rebooting the computer?).
Now it works!

**Comment by sgallou** [comment]
Yes, restart only Yadoms should be necessary.
Thanks for your help.
