### ISSUE TITLE
Not every equipment is available in widget configuration

### ISSUE THREAD

**Issue by klorydryk** [Yadoms/yadoms#250]
I have my 7 ZWave equipments in the Yadoms list: Smoke Sensor, 2 Wall Plug, 3-in-1 Sensor, Dimmer Module, simple Motion Sensor, and 1 RGBW Controller.

When I open a "switch", I should at least have in the list my 2 wall plug (same constructor/model). But only one of them is in the list.
In an "indicator", I should be able to display motion sensor state, or the smoke sensor state. But only the same wall plug as the switch is displayed... and the system.

**Comment by jano42** [comment]
Should be fixed in 2_0_0
