### ISSUE TITLE
weather widget: no source

### ISSUE THREAD

**Issue by klorydryk** [Yadoms/yadoms#251]
Raspberry 2.0.0 rc2 package installation.

I've completed the GPS position in Yadoms configuration, but in the weather widget doesn't offer to choose a source of data: the equipment list is empty.

**Comment by sgallou** [comment]
You have to add a weather plugin (WeatherUnderground : the only weather plugin available for now). Yadoms doesn't get weather data itself.

**Comment by klorydryk** [comment]
Ok, I understand that it is linked to #246 !

**Comment by sgallou** [comment]
I don't think so, because WU plugin should already be installed. Just go to "Plugins"/"Create a new plugin" and choose "Weather Underground".

**Comment by klorydryk** [comment]
Ok, I understand now. It works, thanks. It could be interessant to add this information in the widget description ;)

**Comment by sgallou** [comment]
Ok, thanks for your remark.
