### ISSUE TITLE
Python automation rules: no help

### ISSUE THREAD

**Issue by klorydryk** [Yadoms/yadoms#252]
Raspberry img 2.0.0 rc2

The "Display API script help" open a 404:
`Page 404 : file not found : scriptInterpreters/ypython27/yScriptApiDoc.md`

**Comment by sgallou** [comment]
Not fixed in RC3

**Comment by jano42** [comment]
The path is badly generated for unix system (the path is lowerCased and must not).
Fixed in branch 2_0_0
