### ISSUE TITLE
No data keyword on AD142 Plug-in Dimmer Module

### ISSUE THREAD

**Issue by klorydryk** [Yadoms/yadoms#253]
My dimmer "AD142 Plug-in Dimmer Module" is listed in the equipments list, but there is no data keyword associated. So it can't be controlled (I don't know how to call it from a python rule, and it is not listed in the dimmer widget).

**Comment by jano42** [comment]
Ok ! This is due to our third party library (openzwave) which do not already support your device

I'm upgrading it to last nightly build; and I will make a try, so it could be controlled basically.

Then I could send you files, in order to make you test with the device.

**Comment by klorydryk** [comment]
I'll do it!

**Comment by jano42** [comment]
Just let a try.

1. Power off yadoms (or just Zwave plugin)
2. Replace (make backup) the file manufacturer_sepcific.xml by the file contained in [manufacturer_specific.zip](https://github.com/Yadoms/yadoms/files/989359/manufacturer_specific.zip). The location is next to yadoms executable folder in : /plugins/ZWave/config/manufacturer_sepcific.xml
3. Restart yadoms (or just ZWave plugin)
4. Wait for a few seconds, and look at "dashboard -> devices", if the AD142 now contains childs (by chossing it in the list) (=> dont hesistate to send screenshots of [gif](http://www.screentogif.com/))




Let me know

**Comment by klorydryk** [comment]
I did that... and it doesn't work better :(
![dashboard -> devices->AD142](https://framapic.org/wDFb46vsy8IS/yVS4wpfQZVFZ.png)
I promess I used the right file!
`-rw-r--r--  1 pi pi 56844 May 10 11:40 manufacturer_specific.xml`
`-rw-r--r--  1 pi pi 56814 May 10 22:06 manufacturer_specific.xml_old`

**Comment by jano42** [comment]
@klorydryk : have you try to reboot the raspberry and yadoms ? Sometime ZWave plugin (due to OpenZwave third party lib) need to be rebooted to make it work properly.

**Comment by klorydryk** [comment]
Just rebooted the raspberry. Still nothing :(

**Comment by jano42** [comment]
Probably fixed with current branch (rc6).

@klorydryk : would you like I sent you the current rc6 version in order to let you check if issue is still available ?
