### ISSUE TITLE
Gauge display '%' for temperatures

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#255]
Tested with EnOcean temperature sensor and fakePlugin/fakeSensor

![image](https://cloud.githubusercontent.com/assets/6855339/25919103/eab3a9a8-35cd-11e7-9543-824d4ed0e3b7.png)

**Comment by jano42** [comment]
Not reproduced !

**Comment by sgallou** [comment]
Still reproductible.
More precision : the unit is not updated when you select another keyword :
* Instanciate gauge
* Select temperature keyword.  '°C' will be displayed ==> OK
* Edit the gauge
* Select a dimmable keyword. '°C' is still displayed ==> ERROR

**Comment by jano42** [comment]
Fixed in branch 2_0_0
