### ISSUE TITLE
[Blockly] WaitForEvent selection order rise an error

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#258]
When configuring a WaitForEvent block :
* Connect a "when device emits data" sub-block
* Remove this sub-block
* Connect a "every minute" sub-block
* Finish the rule (ie add an log action)
==> Saving rule is impossible (error raised "please select correct value from list")

![blockly2](https://cloud.githubusercontent.com/assets/6855339/25923264/e98760b0-35dc-11e7-824f-f3e4f426e62f.gif)

**Comment by jano42** [comment]
Fix in branch 2_0_0
