### ISSUE TITLE
[Blockly] "At specific dateTime" sub-block accepts time-only block

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#259]
![atspecificdatetimeacceptstime](https://cloud.githubusercontent.com/assets/6855339/25935367/2e178458-3623-11e7-9b72-eb7344671a8b.gif)

And then fails :

> Log file created/rotated Thursday, 11 May 17 06:23:06 GMT
> Thu, 08:23:06 : [Information] : #### START ####
> Thu, 08:23:06 : [Information] : Script started
> Thu, 08:24:00 : [Error] : Traceback (most recent call last):
> Thu, 08:24:00 : [Error] :   File "scriptCaller.py", line 38, in <module>
> Thu, 08:24:00 : [Error] :     script.yMain(yApi)
> Thu, 08:24:00 : [Error] :   File "D:\Projets\Domotique\yadoms_master\builds\DEBUG\scripts\locals\rule_2\yadomsScript.py", line 17, in yMain
> Thu, 08:24:00 : [Error] :     if waitForEventResult.getType() == scriptUtilities.WAITFOREVENT_DATETIME and scriptUtilities.strToDateTime(outVar) == scriptUtilities.toDatetime(time(12, 0)):
> Thu, 08:24:00 : [Error] :   File "D:\Projets\Domotique\yadoms_master\builds\DEBUG\scriptInterpreters\yPython27\scriptUtilities.py", line 76, in toDatetime
> Thu, 08:24:00 : [Error] :     return datetime.combine(datetime.date.today(), object)
> Thu, 08:24:01 : [Error] : AttributeError: 'module' object has no attribute 'combine'
>

**Comment by jano42** [comment]
Fixed in branch 2_0_0
