### ISSUE TITLE
Install/Update page : Icon not displayed

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#261]
Just a bad URL for scriptInterpreters :
http://.../scriptInterpreters/y **_p_** ython27/icon.png
instead of 
http://.../scriptInterpreters/y **_P_** ython27/icon.png)

![image](https://cloud.githubusercontent.com/assets/6855339/25998541/c2c11674-3721-11e7-9c73-d9ca8535797a.png)

**Comment by jano42** [comment]
Fixed in branch 2_0_0
