### ISSUE TITLE
Unable to edit  the most Blockly rules

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#263]
All rules containing waitForEvent block configured to wait for a new acquisition is not editable, because of the commit 8a4c787a07fcc828c7ffdecd5455fe3fb649b73c .

Declaration of validationArray doesn't work, and next call to addValidationFunction will fail with error "Uncaught ReferenceError: validationArray is not defined".

**Comment by jano42** [comment]
Fixed in branch 2_0_0
