### ISSUE TITLE
No widget for RGB led controller

### ISSUE THREAD

**Issue by klorydryk** [Yadoms/yadoms#266]
There is actually no way to control my "FGRGBWM441 RGBW Controller". Is there any schedule to provide a widget in order to pick a color for this controller?
Thanks !

**Comment by jmberhault** [comment]
Hello, I will create a widget for this controller for July.

**Comment by jmberhault** [comment]
We have begin some modifications. The widget development will begin this week

**Comment by jmberhault** [comment]
Hello, I have created a first working widget for your need. Its is tested with a real RGBW Zipato Bulb 2 Zwave Led lamp. And I have one question : 
- The lamp, could not generate from the color picker dark colors. it generate the correct correct, but with more intensity. The intensity is controlled by an other device parameter "Level". Is it the same for you ?

**Comment by jmberhault** [comment]
present now in branch 2_0_0
