### ISSUE TITLE
[win10] Installer V2.0.0 rc4 does not complete successfully

### ISSUE THREAD

**Issue by dgateau** [Yadoms/yadoms#269]
On Windows 10 (maybe others?), when installing Yadoms using installer, the application does not start : require "msvcr12.dll" (VS2013 redistributables needed?)
Same behavior when using the "portable" version of yadoms.

**Comment by jano42** [comment]
This is our installer generation do not include vc++ redistributables. We'll fix it asap. 

You can install redistributables on your win10 to make it workable

**Comment by sgallou** [comment]
No need to install redistribuable. Needed dependencies are embedded in Yadoms package.

**Comment by jano42** [comment]
Bad fix. Redistributables must be included inside installer.

**Comment by sgallou** [comment]
This msvcr inclusion is well admitted ([see this page](https://www.microsoft.com/fr-fr/download/details.aspx?id=40784)).
In our case, it's the best solution because :

- no system modification
- not system dependent (Yadoms is still portable)
- installer more light
