### ISSUE TITLE
[Equipement settings] Incorrect combo value available

### ISSUE THREAD

**Issue by dgateau** [Yadoms/yadoms#271]
On Equipement management page, when entering the "Modify a data" page (green icon available for some equipement), the last choice displayed in the combo is "function(index) {this.splice.apply...". (see 
![modif plugin ouvrant combo ko](https://user-images.githubusercontent.com/29263034/26901096-db800c66-4bd4-11e7-9d30-4e2f4ff47864.png)

**Comment by jano42** [comment]
Fixed in branch 2_0_0 (rc5)
