### ISSUE TITLE
Plugin RFPlayer : translation for commands

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#274]
Enum Command should be translated : ON/OFF/DIM/ALL_ON/ALL_OFF/ASSOC for a better understanding.

**Comment by jmberhault** [comment]
I could see this : 
    "EBlyss": {
      "name": "",
      "values": {
        "Off": "OFF",
        "On": "ON",
        "Dim": "DIM",
        "AllOff": "Tous ON",
        "AllOn": "Tous OFF",
        "Assoc": "Trame d'appairage"
      }
    }
Normally, BLYSS don't have assoc ... I could not see these translation into the client web page.

**Comment by jano42** [comment]
According to RfPlayer spec 1.9

![image](https://user-images.githubusercontent.com/3135683/27627394-ee4d85e0-5beb-11e7-983a-a25d5e2d8227.png)

Blyss devices may handle the command "Assoc"

**Comment by jmberhault** [comment]
fixed in branch 2_0_0.
