### ISSUE TITLE
Plugin RfPlayer : ID for Somfy equipement

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#275]
In Yadoms, we could create the device with some ID. We could create an ID with the Ziblue configurator also from an letter (A to P), and a number (1 to 5), it's also the same for a blyss equipment. 

Is there any difference between the two meanings ? Perhaps one is better than the other ?

**Comment by jano42** [comment]
Probably fixed by #283

**Comment by jano42** [comment]
Fixed in branch 2_0_0
