### ISSUE TITLE
several export formats not working on the graphic widget

### ISSUE THREAD

**Issue by gascof** [Yadoms/yadoms#277]
@jmberhault 
4 of the 5 possible formats for exporting the graphics are not functionning (Png, Jpeg, Csv and Xls).
The download starts for the Csv file only.

Tested on Chrome/Win10 and on Chrome/Android 5.0.1

On Chrome/Win10, console reports "Uncaught Error: Unsupported export format on this platform: image/png" and the same with the other unsupported formats

**Comment by jmberhault** [comment]
fixed in branch 2_0_0
