### ISSUE TITLE
Plugin RfPlayer : Protocol visonic

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#279]
Cannot received visonic protocol from Atlantic's equipment. The Ziblue configurator received well the element, but no devices are created from Yadoms..

json file : 
ZIA33{ "frame" :{"header": {"frameType": "0", "cluster": "0", "dataFlag": "0", "rfLevel": "-86", "floorNoise": "-96", "rfQuality": "2", "protocol": "2", "protocolMeaning": "VISONIC", "infoType": "2", "frequency": "433920"},"infos": {"subType": "0", "subTypeMeaning": "Detector/Sensor", "id": "640700960", "qualifier": "2", "qualifierMeaning": { "flags": ["Alarm"]}}}}

**Comment by jano42** [comment]
This is strange. I look at json data and it looks like good !
I've got some device using Visonic protocol and it works well.

Have you any error in plugin log file ?

**Comment by jmberhault** [comment]
I have checked : no error.

**Comment by jmberhault** [comment]
not reproducible this evening.
