### ISSUE TITLE
widget chart : rarely exception 

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#280]
A exception rarely raised during retrieve data from the server.
![image](https://user-images.githubusercontent.com/16737541/27494034-67d30578-584c-11e7-8de6-7cacd4fc1cb9.png)

**Comment by jmberhault** [comment]
the message comes from the server.

![image](https://user-images.githubusercontent.com/16737541/27494246-545ff2d4-584d-11e7-82c2-733882ec2905.png)

**Comment by jmberhault** [comment]
This happens also when there some data to return.

![image](https://user-images.githubusercontent.com/16737541/27494339-bff31012-584d-11e7-8ec8-26c062b11b2d.png)

**Comment by jano42** [comment]
Please join database file
there's probably something wrong with keyworf data

**Comment by jmberhault** [comment]
I'm trying to retrieve the information from charts with a slow connexion. The error arrives more often than when I'm in the same network (a local connexion).

It looks like due to a time out during the data exchange.

**Comment by jmberhault** [comment]
fixed in branch 2_0_0.
