### ISSUE TITLE
RFPlayer : start plugin with no equipment

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#282]
If we start the plugin without the equipment, the plugin state is "starting". It should have the state (or equivalent) : "equipment not found".

**Comment by jano42** [comment]
Probably fixed by #283

**Comment by jano42** [comment]
Need an evolution of AsyncSerialPort to have differences between:

- serial port not found (in case of use of an misconfigured plugin, or a serial port name whih have changed)
- serial port open, but no answer from equipments (in case of using physical serial port on computer, but without connected eqipments)

The serial port should manage a machine state like this:
 - opening serial port
 - serial port opened
 - connecting to equipment (may require the caller to provide initiliazation code)
 - connected
 - closed

**Comment by jano42** [comment]
Fixed in branch 2_0_0 by https://github.com/Yadoms/yadoms/commit/2a19d8a2a01989a33e70f5481dfa38d629f9b793
