### ISSUE TITLE
AsyncSerialPort blocking

### ISSUE THREAD

**Issue by jano42** [Yadoms/yadoms#283]
When the plugin RfPlayer starts without the dongle connected, it tries to send packet on port.

But in the end (AsyncSerialPort is used) and is blocked. [line 220](https://github.com/Yadoms/yadoms/blob/2_0_0/sources/shared/shared/communication/AsyncSerialPort.cpp#L220)

As there is nothing connected, the function never returns, so the plugin is blocked. (unable to stop it,...)

![image](https://user-images.githubusercontent.com/3135683/27733872-a9cc9d44-5d98-11e7-8045-9c9de8922f00.png)

I've seen this bug by trying to solve #282 

The issue can be reproduced easily, by adding the plugin RfPlayer, by selected a not connected serial port.

The function should at least throw a timeouut exception....

**Comment by sgallou** [comment]
It's probably caused by using flow control. We have to set up timeouts.
