### ISSUE TITLE
[Widget shutter] Is clickable even if keyword is read-only

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#291]
When using this widget to display window/door state from a opening sensor, the widget remains clickable.
If clicked, widget changes its state, so state doesn't represent the physical window/door state.

**Comment by jano42** [comment]
Can't reproduce.
Tested with fakePlugin : fakeOnOffReadOnlySwitch and it works well !

Please give more details

**Comment by sgallou** [comment]
You're right. My problem come from keyword badly declared as R/W (correctly declared as R/O now, but was not changed in database. I have to remove/redeclare them).
