### ISSUE TITLE
[RFXCom] Many parasite devices

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#292]
Some devices are created when receiving bad messages (no CRC on message to control its validity). Filter doesn't work.

@jmberhault Please send precise logs with some cases

**Comment by jmberhault** [comment]
additional information will be in developer mode or in trace mode ?

**Comment by sgallou** [comment]
Trace mode

**Comment by jmberhault** [comment]
I have rebooted my Pi this evening with yadoms in trace mode ... More information soon.

**Comment by jmberhault** [comment]
For PT2262, you don't have also security, the equipment send the id, thats all. So the id could be missreceived, and the plugin create a new equipment. During the last week more than 10 new equipments PT2262 have been created ... I'm not sure that a new one each time ...

21:43:05 : mainThread : [Information] : New device : 0.12516847 (PT2262)
21:43:05 : mainThread : [Information] : 
| TREE START
|-type : 19
|-subType : 0
|-id : 12516847
| TREE END

**Comment by sgallou** [comment]
To be tested

**Comment by jmberhault** [comment]
The filter is now OK for the PT2262. I think some ids are emitted randomly, nearly to 10 by days around my house. Now after 3 days, only 2 devices are created in Yadoms. I will investigate, but I think it's some others devices we click on it. I let you deploy this filter on other devices for the RFXCOM.

**Comment by sgallou** [comment]
The commit fe3a3b1dd1c42ccecf680a8a2595bb93e99ab4f1 filters Security1 protocols. This should fix this issue.
To be tested.
A better solution should be to disable automatic pairing, and add a custom command to start pairing.
