### ISSUE TITLE
Blocky : Nothing append when click the Ok button with a specific program

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#295]
To enhance the sending of notifications when the battery of an equipment is low, I would like to add the equipment name into a list, please find below the program :

![capture du 2017-07-16 15-59-18](https://user-images.githubusercontent.com/16737541/28248169-4638b466-6a40-11e7-892b-360931d00ab7.png)

When I finish this program, I click "Ok", and nothing appends. I could notice that I have one processor full with a chrome processus. This looks like a infinite loop, during the generation of the script file. python scripts is not created.

![capture du 2017-07-16 15-59-49](https://user-images.githubusercontent.com/16737541/28248170-463e36e8-6a40-11e7-897c-a7be7a8b1130.png)

**Comment by jmberhault** [comment]
I have created this evening a script step by step and the trouble appears when we insert the block "dans la liste" in the if condition : 

![image](https://user-images.githubusercontent.com/16737541/28541642-0b6d53e8-70ba-11e7-99dc-c6c8b5ea898a.png)

**Comment by jano42** [comment]
Fixed in branch 2_0_0

**Comment by jmberhault** [comment]
I have tested, it's now ok, no bug.
