### ISSUE TITLE
Data exchange between web client and server

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#298]
keywords looks to be asked 2 times by the web client : 

below, some examples from wireshark captures:

![lastdata1](https://user-images.githubusercontent.com/16737541/28479452-cba6481e-6e5c-11e7-8af8-76e35f44a840.png)

![lastdata2](https://user-images.githubusercontent.com/16737541/28479454-ce8011a0-6e5c-11e7-80a0-f877d1cd24ae.png)

the server also answer twice, if the information is redundant ! In bold, we could retrieve two 104 keywords answers from the server.

HTTP/1.1 200 OK
Date: Fri, 21 Jul 2017 19:18:01 GMT
Connection: Close
Server: 2.0.0-rc.5
Content-Type: application/json

{"result":"true","message":"","data":{**"104"**:{"date":"20170721T211530.450074","keywordId":"104","value":"{\"Units\":{\"temperature\":\"data.units.degreesCelcius\",\"speed\":\"data.units.metersPerSecond\",\"humidity\":\"data.units.percent\",\"rain\":\"data.units.millimeter\"},\"city\":\"Feurs\",\"Conditions\":{\"Time\":\"Fri, 21 Jul 2017 21:15:30 +0200\",\"WeatherCondition\":\"Cloudy\",\"Temp\":\"19.1\",\"Pressure\":\"1013\",\"Visibility\":\"N\\\/A\",\"UV\":\"0.0\",\"DewPoint\":\"17\",\"MaxWind\":\"0\",\"AveWind\":\"0\",\"AveWindDegrees\":\"146\",\"Humidity\":\"88%\",\"RainDay\":\"3\",\"FeelsLike\":\"19.1\",\"WindChill\":\"NA\"}}\n"},**"104"**:{"date":"20170721T211530.450074","keywordId":"104","value":"{\"Units\":{\"temperature\":\"data.units.degreesCelcius\",\"speed\":\"data.units.metersPerSecond\",\"humidity\":\"data.units.percent\",\"rain\":\"data.units.millimeter\"},\"city\":\"Feurs\",\"Conditions\":{\"Time\":\"Fri, 21 Jul 2017 21:15:30 +0200\",\"WeatherCondition\":\"Cloudy\",\"Temp\":\"19.1\",\"Pressure\":\"1013\",\"Visibility\":\"N\\\/A\",\"UV\":\"0.0\",\"DewPoint\":\"17\",\"MaxWind\":\"0\",\"AveWind\":\"0\",\"AveWindDegrees\":\"146\",\"Humidity\":\"88%\",\"RainDay\":\"3\",\"FeelsLike\":\"19.1\",\"WindChill\":\"NA\"}}\n"}}}

It would be a great optimisation to ask 1 time the data (ask at the first reading), so through Internet, you divide by 2 the volume of data ... And to check into the server if a keyword is present twice (or more !) into the frame.

**Comment by jano42** [comment]
In which case ?
Please explain how to reproduce (simply with widgets ? in dashboard ?)

**Comment by jmberhault** [comment]
fixed in branch 2_0_0
