### ISSUE TITLE
Libellés "undefined" dans RFXCom

### ISSUE THREAD

**Issue by KptnCavern** [Yadoms/yadoms#300]
![image](https://user-images.githubusercontent.com/30448650/28595206-1557f442-7193-11e7-9acc-7b65e0a08bd6.png)

Pour sélectionner les protocoles que l'on désire, ce n'est pas simple >_<

**Comment by KptnCavern** [comment]
Précisions : c'était sur Windows 10 et Firefox. 
Depuis j'ai testé sur Chrome sous Android et là j'ai les libellés... 
Ahhh les joies des fonctionnements différents suivant des OS et navigateurs :)

**Comment by jano42** [comment]
Je n'ai pas réussi à reproduire.

Testé avec Windows 10 (pro version 1703) et Firefox (54.0 et 54.0.1).

Testé avec Yadoms 2.0.0-rc.5 ainsi que la rc6 en cours de développement.

Pouvez vous regarder dans la console de Firefox si vous avez des erreurs svp lorsque vous êtes sur la page ? (F12 puis onglet console; les erreurs apparaissent en rouge)

Quelle version de Firefox avez-vous ?

**Comment by KptnCavern** [comment]
Finalement j'ai refait le test (depuis lors je n'ai utilisé que mon smartphone... pas trop le temps d'utiliser mon PC en ce moment >_<') et les libellés sont revenus.
Ça devait donc provenir du cache pourtant j'avais fait le test en vidant les caches navigateurs, par contre je ne me souviens plus si j'avais retesté après avoir redémarré la pi.
Ce n'est donc pas un bug systématique (les pires à débugguer !), si lors de tests futurs j'arrive à le reproduire, je complèterais. En attendant ce n'est plus du bug critique non plus.

Sinon pour compléter, j'ai Firefox 54.0.1 32bits. C'est arrivé lors du tout 1er test (donc la pi venait tout juste d'avoir son image de la 2.0.0-rc5 dans sa SD-Card)
