### ISSUE TITLE
Create a new tab and move widget in 

### ISSUE THREAD

**Issue by KptnCavern** [Yadoms/yadoms#302]
After creating a new tab in the personalization mode, I inserted 3 widgets I created in the main tab.
When I left the personalization mode, my widgets disappeared (they were not in the new tab nor in the main tab), and lots of error appeared in the bottom right of the screen.
The last errors I had are in the screenshot bellow:
![temp1](https://user-images.githubusercontent.com/30448650/29092843-fcc1cd5e-7c87-11e7-899e-e0b809be4110.png)

Then the pi cannot be reached again. I had to restart the pi manually.
After the restart, I had my widgets I wanted to move still in the main tab. I moved them again with the personalization mode and it worked. No error occurred.
I have not made more try, but perhaps that the error occurred when you create a new tab and move widgets without leaving the personalization mode between the actions.

My configuration: windows10 + firefox 54.0.1 32bits + pi3 + Yadoms 2.0.0-rc.5 + rfxcom

**Comment by KptnCavern** [comment]
I've made a new try and confirm my hypothesis: if you create a new tab and move a widget to this new tab without leaving the personalization mode, you crash the system.

**Comment by sgallou** [comment]
Please send logs

**Comment by sgallou** [comment]
You can use FileZilla to access RPi. SSH must be enabled on the Pi (It's the default in our Pi image).
In Filezilla, select SFTP as protocol, normal authentification. Use SSH login (see [here](http://www.yadoms.com/blog/2017/05/22/tuto-3-activer-le-wifi-sur-une-raspberry-pi-3/) for default login/password).

The Yadoms log folder is in /opt/yadoms

**Comment by jmberhault** [comment]
I have experience one time this crash this evening with my pi. No information in log files ... I will try to reproduce it under windows.

**Comment by jmberhault** [comment]
crash with Linux : 

![image](https://user-images.githubusercontent.com/16737541/29267776-7adec8fc-80ea-11e7-8c63-572e65af570b.png)

**Comment by jmberhault** [comment]
In ws/FrameFactory.cpp, an exception occured, the function returns boost::shared_ptr<CFrameBase>() not instantiated ... This looks ok (indicated in comments when a exception occurs, the return is null).

But in WebSocketRequestHandler.cpp, in kReceived (l. 152) case we ask for the type, from a pointer not instanciated. The type should be AcquisitionFilterValue or kIsAliveValue.

Two problems:
- The filter message from the web client looks not well formated.
- the case of the message CFrameBase null is not properly treated.

**Comment by jmberhault** [comment]
fixed in branch 2_0_0.
