### ISSUE TITLE
[Chart] Data not visible in "1 month" view

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#303]
Data from last month not visible in "1 month" view, but exist in "6 months" view.

![chart](https://user-images.githubusercontent.com/6855339/29118725-6959c018-7d03-11e7-8867-f38fafb39e5e.gif)

**Comment by jmberhault** [comment]
Please send me your database to test with the latest 2_0_0 branch.

**Comment by jmberhault** [comment]
Already fixed in branch 2_0_0.
