### ISSUE TITLE
Backup doesn't work

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#310]
User configuration backup doesn't work or is not enough efficient.
At least 2 problems :
* Only database is backup : scripts and data must be added
* Backup take too much time

**Comment by jano42** [comment]
Such a procude must be applied:

1. make en temp dir
2. copy the database into temp folder
3. copy scripts into temp folder
4. copy data into temp folder
5. zip temp folder
6. make it downloadable
7. cleanup temp folder

**Comment by jano42** [comment]
Fixed in branch 2_0_0
