### ISSUE TITLE
Bad display of switch widget with last shape

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#312]
Text is not well localized :
![image](https://user-images.githubusercontent.com/6855339/30325049-7304c164-97c3-11e7-9cf9-2659dcde0e8f.png)

**Comment by jmberhault** [comment]
This behaviour is present with Firefox 40.0 ... a very old browser ... not in Firefox v55.0.3/ not in Chrome.

**Comment by sgallou** [comment]
No more reproduced

**Comment by sgallou** [comment]
Still available with current version (31/10/2017) of 2_0_0 branch :
![image](https://user-images.githubusercontent.com/6855339/32240850-bfe6a520-be6e-11e7-9fd3-52b56a5a5c63.png)

**Comment by jmberhault** [comment]
I cannot reproduce this behaviour (through Internet, or locally with chrome 61.0.6103).

**Comment by jano42** [comment]
Can't reproduce

**Comment by sgallou** [comment]
Only visible on Chrome (Windows 10) :
Tested today with the last version of 2_0_0 branch.

Firefox on the left, Chrome on the right.

![image](https://user-images.githubusercontent.com/6855339/32805506-f4c5f5c2-c989-11e7-80d9-bf8ea5b8fd03.png)

**Comment by jano42** [comment]
@sgallou : please send me your database. This could be a consequence of mixing many widgets...

**Comment by sgallou** [comment]
Seems to work now, maybe another browser cache side effect
