### ISSUE TITLE
Error displaying client when connection was lost

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#313]
When reactivate a Yadoms web page after long time (connection lost ?), we got a lot of errors and display is wrong, probably because security token is obsolete.
This case must be identified by the web client, and a full refresh should be initiate (and logging information asked to user).

**Comment by jmberhault** [comment]
With client PCs, with chrome, it's working, the web client reconnect after 30s.

**Comment by jano42** [comment]
How to reproduce ?
I've tested with Windows10/Chrome and no problem after one night of page inactivity.

**Comment by sgallou** [comment]
Did you try with a local server ? I think it's easier to reproduce with distant server.
