### ISSUE TITLE
GUI : Missing color picker .css

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#317]
![image](https://user-images.githubusercontent.com/16737541/30729809-8ce83ce0-9f62-11e7-804f-a1781bb13c9b.png)

**Comment by jmberhault** [comment]
Widgets RGB Color Color and RGBW Color Picker are not available !

**Comment by jano42** [comment]
It seems that www/libs/bootstrap-colorpicker have been changed. => the folder do not contains only the distribution files; but the whole github project !

I'll roll it back to keep only usefull files

**Comment by jano42** [comment]
Fixed in branch 2_0_0
