### ISSUE TITLE
GUI : Wrong icon position when many pages in configuration mode

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#318]
![image](https://user-images.githubusercontent.com/16737541/30729963-a86ba398-9f63-11e7-8986-2ecc9945f365.png)

**Comment by jano42** [comment]
Fixed in branch 2_0_0

![tab_customization](https://user-images.githubusercontent.com/3135683/30746211-47e55e88-9fa9-11e7-80a1-cf0a67487808.gif)
