### ISSUE TITLE
No widget displayed with SAFARI

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#319]
![image](https://user-images.githubusercontent.com/16737541/30755025-50df61e8-9fc5-11e7-9604-ca5f36ee1bba.png)

**Comment by jmberhault** [comment]
logs : 
![image](https://user-images.githubusercontent.com/16737541/30762422-47ae92de-9fe2-11e7-8c52-549e02a520a4.png)

**Comment by jmberhault** [comment]
Better support of safari by the commit : 80bcb47f8a9cbd4e9bde934dbbf7b0ea9e882470

**Comment by jmberhault** [comment]
websockets need login with Safari ? :
 
![image](https://user-images.githubusercontent.com/16737541/30762929-4e799710-9fe4-11e7-8229-114bdc78a538.png)

**Comment by jmberhault** [comment]
It's working well without authentification. Some web articles relate about basic authentification with websockets doesn't works with Safari.

**Comment by jano42** [comment]
Issue confirmed.

- widgets never displayed
- websockeet closed prematurely

Tested : with and without authentication

**Comment by jano42** [comment]
Maybe bad issue.
Safari is no more supported on Microsoft Windows.
The version used in first screenshot of this issue indicate what it is an old version (about 5.xxx).
In MacOS, versions are 9, 10, 11...

**Comment by jano42** [comment]
Not reproductible with Safari 11.

This issue is only targetting safari v5 for Windows. Has safari v5 is deprecated; this issue is not suitable.

**Comment by jmberhault** [comment]
websocket with authentification is not supported with Safari for iMac. Return message 401. More information in next message.

**Comment by jmberhault** [comment]
Safari : 11.0.2 (12604.4.7.1.6) - macOS Sierra version 10.12.6

<img width="1680" alt="telechargement" src="https://user-images.githubusercontent.com/16737541/34890135-a3f8f1ae-f7c8-11e7-97ef-551fee169d9b.png">

**Comment by jmberhault** [comment]
some workaround exists :
https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api
