### ISSUE TITLE
Yadoms shutdown

### ISSUE THREAD

**Issue by jano42** [Yadoms/yadoms#32]
Shuting down (Ctrl-C) Yadoms server when rules are running doesn't work.

Reported by: sgallou

**Comment by sgallou** [comment]
Not better. Tested without rule, and with 1 instance of FreemobileSms plugin.
Application is hold at exit of the try block of CSupervisor::run method (supervisor.cpp line 178) because some references are still hold from another threads.

**Comment by sgallou** [comment]
Sometimes, Yadoms still doesn't want to close, need to be manually killed. See attached log.

[yadoms.log.txt](https://github.com/Yadoms/yadoms/files/125428/yadoms.log.txt)

I add some traces to better understand what happens (806b68b78f1af8a09ea38423ec5537a2ac498888).

**Comment by sgallou** [comment]
No more seen for a long time ==> closed
