### ISSUE TITLE
Capability to place a widget on user choice (not in a sequence)

### ISSUE THREAD

**Issue by guitwo63** [Yadoms/yadoms#321]
The user should place a widget where he want in the dashboard, even if there is no other widget upfront

**Comment by guitwo63** [comment]
this is a evolution

**Comment by sgallou** [comment]
The reasons of this behavior are :
- This is the best compromise to have a web client working on desktop and mobile platforms (even if there is still work to make all functionalities work nice on mobiles).
- We tried other solutions in the past, but this one is the most satisfying we found : in particular, we tried a solution permitting to place widgets anywhere, but rearrangement of widgets was very ugly when switching on mobile client.

So sorry guitwo63, but we don't plan to change this behavior for now.
