### ISSUE TITLE
[Widget] Change widget display if related device doesn't exist

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#325]
When a device is deleted from Yadoms, the widgets using it should be disabled to signal user that widget won't work anymore : change its display and not responding to clicks.
Widget can become grayed, with a message like "Invalid configuration".
In case of several devices used, one of them becoming inaccessible disable the widget.

I propose to add a function setState(state) in widget API. state is an enum {OK, InvalidConfiguration}.

When a widget realize that a device doesn't exist (because of an error listing its keywords, getting last value...), it call setState(InvalidConfiguration) and widget is disabled.

This function can also be called by widget when validating configuration. We can do some dynamic checks on the configuration (actually only static checks are available, by package.json. Like min/max checks...)

**Comment by jmberhault** [comment]
When the widget is disabled : 
- Should it be registered into the configuration in the database, for the next  web browser startup, disable immediately the widget without initialize it ? Or this state is estimated each time we load the web client ?

**Comment by sgallou** [comment]
Nothing should be added to the widget configuration recorded in database.

Events who can update widget state :

- exception getting device/keyword value or registering for acquisitions on a KW
- configuration updated by user
- displaying the widget (when user switch page or at client load)

In case of InvalidConfiguration, the setState method should take a string "message" to explain the problem to user. For example : setState(InvalidConfiguration, "Device PriseCommandée doesn't exist, please update configuration". This message will be displayed like any others notifications.

2 possible display of the disabled widget :

- An error icon in widget title bar (must also be visible if widget has no title bar), like : ![image](https://user-images.githubusercontent.com/6855339/33369585-3c529064-d4f5-11e7-966f-564d08441c33.png)
The error message should be displayed when mouse is over the image (or over the widget), or when clicking on it.

- Widget entirely grayed

**Comment by jmberhault** [comment]
The widget will be grayed with the icon, and the message will be displayed in a bubble when the mouse is over the icon. Is it ok ?

When the configuration is updated by the user, we are still in configuration mode. So I have also to modify this mode, to display the icon.

I think the icon in the middle of the widget would be better.

**Comment by jmberhault** [comment]
done in branch 2_1
