### ISSUE TITLE
Displaying page after empty page

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#329]
When switching from empty page to non-empty page, this one is not well displayed (non systematic).
Here switching from "alarme" to "système" fails :
![ko](https://user-images.githubusercontent.com/6855339/31517335-dfcf324e-af9b-11e7-96bd-fbaca88d97a3.gif)

If page contents at least one widget, it works well :
![ok](https://user-images.githubusercontent.com/6855339/31517183-7616482e-af9b-11e7-84b2-d4ff073b1b60.gif)

**Comment by jmberhault** [comment]
fix in branch 2.0.0 with commit c856b98985277516916eb67e915acbaa49ee2f6e.

**Comment by jmberhault** [comment]
Could not reproduce this issue in the branch master. 
The only thing is textfit is not applied when we come back in a already loaded page.
