### ISSUE TITLE
[Switch widget] Enter key display push-button form select modal

### ISSUE THREAD

**Issue by jano42** [Yadoms/yadoms#33]
When focusing in the title and press Enter key, the push-button icon selection modal is displayed (see screenshot)

Reported by: sgallou

**Comment by sgallou** [comment]
In configurations (for example in switch widget) containing icon picker, unable to scroll (no vertical scroll bar, mouse roll inactive). So unable to push OK button.
Tested with Chrome

**Comment by sgallou** [comment]
Bug also present in dashboard pages (not only on modals), so transfer into new issue
