### ISSUE TITLE
web client on Edge doesn't work

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#332]
At first start (without any database), the first page is not created on Edge. Refresh the page doesn't help.
No message in console, no error in Yadoms logs...

The only way I found to make Edge create the first page is to open debugger (F12) and refresh the page...

A side-effect is that no data is accessible until first page was created : in dashboard, plugin state is not displayed, values of keyword not displayed too, etc...

**Comment by jano42** [comment]
Displaying the DebuggerTools make the page loads correctly.
Without debuggertools the page nevre loads

**Comment by jmberhault** [comment]
Since the refactoring of the first start (creation of the first configuration), Yadoms is now working with Edge, so Edge is now enable by the commit ba8a766671ce2f2e586d1f6758835594ff8ab0f8
