### ISSUE TITLE
GUI : web client disconnection after some hours

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#339]
After 2/3 hours, the web client is time out :

11:47:01 : Websocket connection : [Trace] : Rest request : [GET] : /rest/eventLogger/from/399
11:48:07 : Websocket receiver thread : [Debug] : Websocket receiveFrame Poco::Exception : Timeout
11:48:07 : Websocket connection : [Information] : Websocket client lost
11:48:11 :  : [Trace] : Rest request : [GET] : /rest/eventLogger/from/399
11:48:16 : plugin.IpcAdapter#14 : [Trace] : [RECEIVE] message 12 from plugin instance #14
11:48:16 : plugin.IpcAdapter#14 : [Trace] : [RECEIVE] message 12 from plugin instance #14
11:48:16 : Websocket connection : [Trace] : Rest request : [GET] : /rest/eventLogger/from/399

**Comment by sgallou** [comment]
Maybe related to #313 ?

**Comment by jmberhault** [comment]
Authentification was not used in this issue.

**Comment by jmberhault** [comment]
Not reproducible after commit 13d9814f2d7c87789ce02872ea4827bee9adbfb0. This problem was due to CPU overload by the web client, with highcharts animation enable after some hours of continious display.
