### ISSUE TITLE
favicon : bad path ?

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#340]
A user sent me its logs, and I saw something strange :
> Global catch Poco::Exception : File not found: www/android-icon-192x192.png
> Global catch Poco::Exception : File not found: www/android-icon-96x96.png

[See the full log](https://github.com/Yadoms/yadoms/files/1404321/yadoms.zip)

This exception was seen for every resolution.

Such file exist in sources\www\img\favicon folder. Do we have a bad path management ? Or alias is missing ?

However, no bad behavior was reported.

**Comment by jano42** [comment]
@sgallou : the fix is provided in branch 2_1. Please retry dispaying Yadoms from your android device

**Comment by jano42** [comment]
In case, there are still errors, I've another code fix to try
