### ISSUE TITLE
Problem after installing a new version of yadoms

### ISSUE THREAD

**Issue by KptnCavern** [Yadoms/yadoms#341]
Minor issue:
When you install a new version (or reinstall the same one), if you keep the database and script but you don't keep the file yadoms.ini (considering that in the new version the file can evolve it is often better not kept it), and if you had select the option "authenticate session" in your previous version, you still have the option after (it's checked), but your session is no more authenticate (login / password it not propose anymore).
You have to uncheck the checkbox and check again to have the authentication back.

**Comment by jano42** [comment]
Either the authentication option should be stored into database
Or consider using update packages

**Comment by sgallou** [comment]
Sorry I can't reproduce it.
And its sounds strange for me as if you keep your database (+ scripts), and reinstall the same version (same executables), nothing differ between the 2 executions, so what can be broken ?
I you know how to reproduce it, give us more information (send me your database+scripts, and the version used).
