### ISSUE TITLE
[Backup] Backup order

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#345]
![image](https://user-images.githubusercontent.com/6855339/31958770-1483b112-b8f3-11e7-8ae4-22c10242afa3.png)

Backup should be ordered by date

**Comment by jmberhault** [comment]
Not yet fixed : 

![image](https://user-images.githubusercontent.com/16737541/36357361-488938ae-14fd-11e8-965e-e69231de2675.png)

**Comment by jmberhault** [comment]
fixed in branch develop.
