### ISSUE TITLE
[Backup] 1 zip out of 2 are not readable

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#346]
On 4 backups done from my Pi, can not open 2 zip files from my PC. Zip file seems corrupted.
No error log server-side (not a lot of log about backup. Maybe need more).

**Comment by jano42** [comment]
Very strange.
Today the file compression is realized with Poco::Zip; which is a lightweight de/compressions library.

I checked the usage and code is good.

Poco::Zip do not expose zip files checking/crc. 

I thing there are two options:
- use boost to create zip file (relatively obscur)
- use an external compress library (but hard to find => corss platform, cross compilation,...)

**Comment by sgallou** [comment]
I think that we have to try with boost first.

**Comment by jano42** [comment]
@sgallou : could you determine if initial zip files are corrupted, or if the download fails

**Comment by jano42** [comment]
Behavior of backup is changing:

- better handle failures. Allow up to 3 tries
- in case of database locked problems, allow also 3 retries with 10s sleep,
- compressing file using filename "xxx.zip.inprogress" and if all is success rename it to "xxx.zip"
