### ISSUE TITLE
Test 2.0.0 : Migration => GUI missplaced widgets

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#352]
After migrating from the RC6 to the 2.0.0 (in testing), at the first time, when browsing from one tab to another, widgets are misplaced (all at the position 0 of the page).

After refresh the web client by pressing "F5", this bug is not reproducible.

Is it due to cache change ?

**Comment by jano42** [comment]
Probably due to cache and manual upgrade.
This should not appear with update process (from dashboard).

**Comment by jmberhault** [comment]
Appears yesterday through Internet one time ... perhaps since the #329 fix, to be investigated.

**Comment by sgallou** [comment]
Appears just now to me, after adding a page. Navigating through pages doesn't restore correct widgets arrangement.
Nedd to quit edit mode and refresh page (F5) to fix display.

**Comment by jmberhault** [comment]
I could reproduce this one in a systematic way.
