### ISSUE TITLE
Adding a page clear antoher one

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#357]
I recently add a page on my client. Since this operation, I saw that another page was entirely cleared (no more widget inside).
In my database, the page still exists (associated tab is displayed in client), but no widget inside.

Before any investigation, I need to try to reproduce this behavior.

**Comment by jmberhault** [comment]
please could you retry now after the fix of the #352 ?

**Comment by sgallou** [comment]
Can't reproduce
