### ISSUE TITLE
Server doesn't start in daemon anymore

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#358]
In branch 2_0_0, it is impossible to start Yadoms in daemon.
Lauching `./yadoms --daemon` does nothing (no error, no log, no process started)

**Comment by jano42** [comment]
Which OS/platform ?

**Comment by sgallou** [comment]
On RPi (not tried under Windows)

**Comment by jano42** [comment]
Tried on Linux.
Same pb

IT WORKS WITH "SUDO"

**Comment by jano42** [comment]
Is it due to /var logging ?
