### ISSUE TITLE
[Blockly] : bad python generation

### ISSUE THREAD

**Issue by jano42** [Yadoms/yadoms#366]
With this rule
![image](https://user-images.githubusercontent.com/3135683/33196211-9743ad66-d0de-11e7-9fa5-f82b68d25e1c.png)

The python generated is 
[yadomsScript.py.zip](https://github.com/Yadoms/yadoms/files/1500667/yadomsScript.py.zip)

Erros are on line 52 and 60

**Comment by sgallou** [comment]
Still a problem :

>                   if waitForEventResult0.getType() == scriptUtilities.WAITFOREVENT_KEYWORD and keywordId0 == null:
>                      print 'Dodo'
>                      yApi.writeKeyword(156, str(int(False)))
>                      break
>                      endOfLoop0 = True
