### ISSUE TITLE
[Blockly] Restore backup

### ISSUE THREAD

**Issue by jano42** [Yadoms/yadoms#367]
Restoring a rule don't match the saved state.

This is random, but sometimes some blocks are detached; sometime devices are lost.

**Comment by sgallou** [comment]
Still fail to restore :
![image](https://user-images.githubusercontent.com/6855339/33280354-1281d8ca-d3a2-11e7-8d66-8687b6df8cc4.png)

Error in console :
![image](https://user-images.githubusercontent.com/6855339/33280384-293893ec-d3a2-11e7-8923-5ddf05a60383.png)

**Comment by jano42** [comment]
Did you recreate rule from scratch ?

If it is the same rule (edit with previous blockly code) it will fail.
You must edit it from scratch ;-(
Same for python generation
