### ISSUE TITLE
[Blockly] Taking a second waitForEvent block is already populated

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#372]
When adding a second waitForEvent block, it already contains 2 sub-blocks, like the first I set in my rule.

![image](https://user-images.githubusercontent.com/6855339/33286340-65c6b4d4-d3b5-11e7-8590-5ade93122edd.png)

**Comment by sgallou** [comment]
Every change on a waitForEvent block change the second one...

**Comment by jano42** [comment]
Have you tested the new version on branch 2_0_0 ? (with cache cleaning)
Automation/Blockly : Fix wait4event block initialization
<https://github.com/Yadoms/yadoms/commit/d8bccb6c60e381433228ea8c855a54735bc6163a>


2017-11-27 21:03 GMT+01:00 Sébastien Gallou <notifications@github.com>:
