### ISSUE TITLE
[Cache managment] Cache need refresh when web client is modified

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#375]
[Tested on Chrome 62]

The only way I found to take account of a new web client version is to open developer mode (F12), go to "network" tab, check "disable cache" and reload the page (F5).
Without opening developer mode, F5, Shift-F5, Ctrl-Shift-R doesn't help to renew the cache.

**Comment by jano42** [comment]
OK. After some reading, I now really understand how cache works.

# Summary

The first time a file is request, the server answers with providing an ETAG and a max-duration
![image](https://user-images.githubusercontent.com/3135683/33426260-80c564f2-d5c1-11e7-9d41-bfc08e68f4da.png)

The next time the browser want to get a file, it checks if it is still available in local cache ( < max-age)

If available, the browser uses the local file, without requesting the server.

If cache file has expired, then it ask the server to get the file, providing the etag from the cache.

![image](https://user-images.githubusercontent.com/3135683/33426265-86b81a80-d5c1-11e7-8a2e-f80019dc871e.png)

**Comment by jano42** [comment]
Fixed in branch 2_0_0
