### ISSUE TITLE
[Backup] Page not refresh at backup end

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#376]
2 points :

## Page refresh
At backup end, page rest at this state : 
![image](https://user-images.githubusercontent.com/6855339/33332031-78476bc2-d463-11e7-9c53-cd2a09d464cf.png)

Nedd to re-click to "Maintenance" tab to refresh the page and see backup in table.

## Temporary file visible in table
If refreshed to early (by clicking on "Maintenance" tab), table shows the ".zip.inprogress" file and hide the progress bar :
![image](https://user-images.githubusercontent.com/6855339/33332213-eeb8212a-d463-11e7-9605-a95f899e42f7.png)

**Comment by jano42** [comment]
Point 1 : page is refreshed, but backup process may be long. So just wait.
Point 2 : if page is refreshed, now if a backup is in progress, the progress bar is shown
