### ISSUE TITLE
[Blockly] devices select comboBox not scrollable

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#377]
[Chrome]

Can not access to the top of the comboBox, the combo is not scrollable (right scrollbar has no cursor, is paint as full)

![image](https://user-images.githubusercontent.com/6855339/33342875-c56bb92e-d483-11e7-980c-0676fc710f2d.png)

**Comment by jano42** [comment]
This is an active issue in Blockly.
Change current issue to next milestone

**Comment by sgallou** [comment]
[This issue](https://github.com/google/blockly/issues/1364) ? Did you try the suggested workaround ?

**Comment by jano42** [comment]
Fixed in branch 2_0_0
