### ISSUE TITLE
[Blockly] Many new non-sense variables

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#379]
What are these variables : 

![image](https://user-images.githubusercontent.com/6855339/33343177-b680b4d6-d484-11e7-968d-9c7fa4f851e4.png)

![image](https://user-images.githubusercontent.com/6855339/33343190-c2767bae-d484-11e7-94ad-031ee2e4e9b2.png)

**Comment by jano42** [comment]
Wha ! All those variables are just created at generation time (when generating python code).

I'll see how to make those variables 'private'

**Comment by jano42** [comment]
Can't reproduce.

**Comment by sgallou** [comment]
Can not reproduced anymore too...
Close issue for now...

**Comment by sgallou** [comment]
Problem seen by another user

**Comment by sgallou** [comment]
Was closed by error

**Comment by jano42** [comment]
Can't reproduce.
Please check reproductivity and provide how(to reproduce.

**Comment by jano42** [comment]
@sgallou : please reproduce or close issue
