### ISSUE TITLE
[widget chart] Doesn't work under Safari

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#380]
[mac : OS X Yosemite Version 10.10.5, Safari : Version 10.1.2]

Please note that this behavior is reproductible with any curve type (on/off type and analog types like temperatures).

With Safari (no error or warning in console) :

![capture d ecran 2017-11-28 a 21 57 30](https://user-images.githubusercontent.com/6855339/33344441-4c936bd6-d489-11e7-88d2-6e16ff02b574.png)

With Chrome :

![capture d ecran 2017-11-28 a 21 58 49](https://user-images.githubusercontent.com/6855339/33344452-56bbd4ae-d489-11e7-9354-1bea3ae06a6e.png)

**Comment by jmberhault** [comment]
check if highchart boost library and useGPUTranslations could cause troubles.

**Comment by jano42** [comment]
This is probably the getTime function which is used many times in viewModel.

https://stackoverflow.com/questions/45433237/highcharts-not-display-for-ios-and-safari

**Comment by jmberhault** [comment]
Working with commit f2865e9
Safari : 11.0.2 (12604.4.7.1.6) - macOS Sierra version 10.12.6
