### ISSUE TITLE
Plugin State : Wrong message format

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#381]
The json string is displayed instead of the custom message id.

![image](https://user-images.githubusercontent.com/16737541/33376647-d0869622-d50e-11e7-9e45-4041c99df8e3.png)

**Comment by jano42** [comment]
The message is intended to be displayed into Dashboard/Plugins (the translation is not done in equipements)

The plugin States should only be displayed for developers. (I thinl it is already the case).

In my point of view, the isue should be closed.

**Comment by jmberhault** [comment]
Yes, it's only available for developers.

**Comment by sgallou** [comment]
Json data is also used for message keywords : 
![image](https://user-images.githubusercontent.com/6855339/33377804-075a705c-d513-11e7-9abf-9a55d50fc737.png)

So a better display should be done, for example like a simple multi-line tree :
to : 1
from : 0
body : Nouvel état du plugin Weather Underground plugin state : Running

or in your case:
messageId : asyncPort.serial.failToOpen
messageData : port : /dev/ttyUSB1

**Comment by jano42** [comment]
Fixed in branch 2_1

Now Json value are pretty printed :
![image](https://user-images.githubusercontent.com/3135683/35029591-f3bcb0c2-fb5b-11e7-908d-05dfb15298c4.png)
