### ISSUE TITLE
RFP1000 : Can't upload a new firmware with Raspberry Pi

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#386]
This action is working well with Windows 7 64 bits. 
The equipment connected to the Raspberry Pi, I'm trying to upload the firmware, I could select the file in my PC (windows 7 - 64 bits), but the state of the plugin stay at running. No "microcode upload..." state.

**Comment by jano42** [comment]
With Yadoms installed on RaspberryPI, it fails when uploading.

![image](https://user-images.githubusercontent.com/3135683/33607715-42b6a5a4-d9c2-11e7-9821-e674c153f305.png)

**Comment by jano42** [comment]
The uploaded file received by plugin is good.

I've tested by writing firmware content to raspberry local file; then compare source file (from Windows) and written file (rpi)
=> the files are the same

@sgallou : please check if firmware upgrade works on RaspberryPI with Rfxcom plugin

**Comment by jano42** [comment]
Fixed in branch 2_0_0 by https://github.com/Yadoms/yadoms/commit/fda8ff66a35db697604f8e1cba8ce701f63a61c6

This is due to a boost method which is not efficient on embedded hardware.
