### ISSUE TITLE
Long refresh time for devices in devices page

### ISSUE THREAD

**Issue by jano42** [Yadoms/yadoms#39]
The refresh time of the devices page, could be sometimes very long (with a Pi, with a Pi2).

Reported by: jmberhault

**Comment by jmberhault** [comment]
After clicking "Devices", and one equipment, the yadoms load goes up and stay at 100%.

![yadoms load](https://cloud.githubusercontent.com/assets/16737541/14233574/e645f0bc-f9cc-11e5-816d-27c371d71a20.png)

**Comment by jano42** [comment]
Fix by adding indexes on database
