### ISSUE TITLE
[Widgets] Add a widget displaying Wind

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#393]
Ideally user can choose between different display types : 

1. Arrow for direction, colored for speed : 
![image](https://user-images.githubusercontent.com/6855339/33652535-1db2d90a-da6a-11e7-864c-aeba51d76f73.png)

2. On a circle
![image](https://user-images.githubusercontent.com/6855339/33652557-34bc04be-da6a-11e7-8e9f-8079f5b8ca23.png)

3. Arrow + text
![image](https://user-images.githubusercontent.com/6855339/33652586-4db72a48-da6a-11e7-9455-e7a1e6acfea8.png)

4. Standard symbols
![image](https://user-images.githubusercontent.com/6855339/33652682-967a346e-da6a-11e7-8173-94f41f299d9b.png)

**Comment by jmberhault** [comment]
A first widget that display wind exist since the v2.0.2 revision.
