### ISSUE TITLE
[Yadoms update] Page "Yadoms is updating" must be displayed until reconnection

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#396]
This page is shown some seconds, then gone. So we see the normal web client page, with many error notifications until client reconnect.
It will be nicer to keep the "Yadoms is updating" page until client is reconnected (and suspend error notifications).

**Comment by jano42** [comment]
Not reproductible.

Update workflow seems good. (see attached video => full update)
![update](https://user-images.githubusercontent.com/3135683/54265851-7e5d1e00-4576-11e9-9ea8-4c35446a61d3.gif)
