### ISSUE TITLE
Blockly : click right doesn't work

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#407]
Clcik right on a block open an empty menu. We cannot duplicate, remove, etc ... blocks.

![image](https://user-images.githubusercontent.com/16737541/34179291-a4bf1c6a-e50a-11e7-9ab5-669282e04070.png)

**Comment by jmberhault** [comment]
I cannot select also new devices or keywords.

**Comment by jmberhault** [comment]
With the browser Opera. It's working with Chrome, so I have downgrade the level.

**Comment by jano42** [comment]
Can't reproduce.
Tested with Opera 50.0.2762.45 => working
Tested with Chrome 63.0.3239.132 => working

Both on Windows 10 64 bits.

**Comment by jano42** [comment]
@jmberhault : could you confirm bug is still existing ?

**Comment by jmberhault** [comment]
can't reproduce with Windows 7 64 bits and Opera 50.0.2762.58 => close.
