### ISSUE TITLE
[Plugins page] Progress bar not restored

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#414]
Seems similar to #376 (need probably the same fix).

When flashing RFXCom, a progressbar is displayed.
![image](https://user-images.githubusercontent.com/6855339/34278137-562e6448-e6a9-11e7-9d7f-c9f992d2ca8f.png)

If you refresh the page while flashing, the progressbar is no more displayed :

![image](https://user-images.githubusercontent.com/6855339/34278130-424e9236-e6a9-11e7-968c-fd9ad51d8cc1.png)

**Comment by jano42** [comment]
This is not an easy solvable issue.
In fact when starting a firmware update, the server answer by providing a task id. (the update task which is asynchronous).
Then the page registers for taskNotificationUpdate for the taskid.

If the page is refreshed, the taskid is lost and notifications are not catched.

I suggest to close this issue.
