### ISSUE TITLE
Disk full : => error in dabase return => crash of Yadoms

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#415]
![image](https://user-images.githubusercontent.com/16737541/34289994-6ccdf924-e6f5-11e7-818d-7ef413cf89a0.png)

**Comment by jmberhault** [comment]
![image](https://user-images.githubusercontent.com/16737541/34290019-82356400-e6f5-11e7-8050-4624062a668f.png)

**Comment by sgallou** [comment]
Yadoms provide tools to monitor disk usage (through systemInformation plugin). User can create a simple rule to be notified when disk almost full.
I don't know how to manage securely a such event.
