### ISSUE TITLE
[Widgets manager] Rolling title not updated after title change

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#444]
When I changed the title of an existing switch widget, the rolling title management is not updated and title is truncated.

Compare label in configuration window and the widget title displayed in main page :
![rollingtitlebug](https://user-images.githubusercontent.com/6855339/36388568-908a0cd8-159c-11e8-9201-dd0e2d9a6bdc.gif)

Refresh the page (F5) make title correctly displayed.

**Comment by jmberhault** [comment]
fixed in branch develop.
