### ISSUE TITLE
[Plugin]Pb with numerical parameter in extra query

### ISSUE THREAD

**Issue by KptnCavern** [Yadoms/yadoms#446]
Hi,
I'm developping a new plugin for an adapter for a Somfy remote control (to "manage" the IO protocol)
I've tried to create an extra query to use the "PROG" command (to pair a device with the remote control).
In that query, i've tried to parameter the channel on which the user want to use the PROG command.
I've tried first with a "numeric" parameter, but no pop-in appeared when I used the extra-command.
Then I used "enum" and it worked. So I think there is a problem there (I also tried with the "OrangeBusiness" plugin (which use the same parameter in its extra command) and the extra command has the same problem).

**Comment by sgallou** [comment]
Not reproduced.
Added a specific numeric-data based extra query in fakeplugin to test.
Added user-test on most of extra queries.
