### ISSUE TITLE
REST requests with parameters

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#449]
In the future for better web client performances, REST requests should have parameters and replace the getLastValue, or getLastValues requests.

The new request souhld be able to return :
- the capacity
- RO ou RW
- the friendlyname
- the type (enum, json, nodata...)
- the unit (W, Kwh, ...)
- the information about the type (values list for enum, ...)
- absolute or relative values
- details
- the value of the last acquisition
- the date of the last acquisition

**Comment by sgallou** [comment]
Refactor some REST request :

- add PUT acquisition/keyword/info request to get several infos for several keywords. Takes 2 parameters : the list of keywords and the list of infos (see above for available infos)
- change PUT acquisition/keyword/lastdata behaviour : now returns only the last acquisition value (no more date). JSON tree returned was updated.
- add PUT acquisition/keyword/*/info request to get several infos for one keyword, takes 1 parameters : the list of infos (see code for available infos)
- change GET acquisition/keyword/*/lastdata behaviour : now returns only the last acquisition value (no more date). JSON tree returned was updated.

Available infos are :

- lastValue
- lastValueDate
- deviceId
- pluginId
- capacity
- accessMode
- dataType
- unit
- typeInfo
- measure
- details

**Comment by sgallou** [comment]
Widgets need to be updated
