### ISSUE TITLE
New plugin/widget present to download

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#455]
The number of new plugins or widgets not presents locally, should be indicated in a circle in blue or red, in the menu (today not present) : 

![image](https://user-images.githubusercontent.com/16737541/38211277-4110572c-36ba-11e8-879b-6ac228e9ce71.png)

For example, for an update :

![image](https://user-images.githubusercontent.com/16737541/38211320-58812f9e-36ba-11e8-9979-742cde85417c.png)

**Comment by sgallou** [comment]
After team discussion, won't fix
