### ISSUE TITLE
Cannot delete invalid plugin

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#457]
When a plugin is invalid, it is displayed like this : 

![invalidplugin](https://user-images.githubusercontent.com/16737541/38212541-65e1bcfe-36be-11e8-867d-2b50277753d9.png)

This would say, that a main file is missing.

But, when missing the package.json file, the icon.png file, a plugin could not be deleted, and theses errors are returned. Yadoms crash after try to delete it !

21:30:03 : Websocket connection : [Information] : New websocket client
21:30:07 :  : [Error] : Global catch Poco::Exception : File not found: plugins/Sigfox/package.json
    in thread : TCPServerConnection (default[#3])

21:30:07 :  : [Error] : Global catch Poco::Exception : File not found: plugins/Sigfox/icon.png
    in thread : TCPServerConnection (default[#4])

The plugin should be deleted in the database anyway.

**Comment by sgallou** [comment]
Unable to reproduce : try with FreeMobileSms plugin :
* create a plugin, delete package.json (plugin marked as invalid) ==> delete plugin with no error
* create a plugin, delete package.json and icon.png (plugin marked as invalid) ==> delete plugin with no error

**Comment by jmberhault** [comment]
Unable to reproduce with SystemInformation and Sigfox plugins with Windows and Linux with Yadoms v2.2.0-beta.1 => close.
