### ISSUE TITLE
Yadoms : Update plugin

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#458]
I have delete locally in pi the plugin Sigfox to be able to install it a new time, but Yadoms, don't show me the plugin in the "update & Install" page, becase, I have this element return : 

_21:51:55 : scanForUpdates : [Debug] : Build updates data (with prereleases)...
21:51:55 : scanForUpdates : [Warning] : Invalid remote package for Sigfox, will be ignored
21:51:55 : scanForUpdates : [Debug] : exception : Invalid parameter version : No such node (version)
21:51:55 : scanForUpdates : [Debug] : Build updates data (releases only)...
21:51:55 : scanForUpdates : [Warning] : Invalid remote package for Sigfox, will be ignored
21:51:55 : scanForUpdates : [Debug] : exception : Invalid parameter version : No such node (version)
21:51:56 : scanForUpdates : [Debug] : scanForUpdates report progression 100 with message scanForUpdates.success
21:51:56 : taskScheduler : [Information] : Stopping thread Task scanForUpdates_

But all Sigfox packages into the FTP have the version node ... And when sigfox was present locally, I was able to update the plugin ...

Try by yourself.

**Comment by sgallou** [comment]
Your package.json is encoded in ANSI, but it must be encoded un UTF8. Please change encoding and retry (don't forget to also update package.json located in zip file).

**Comment by jmberhault** [comment]
No, the update was done properly, when an old package was present locally.
When no package is present locally, I could not download the package.
