### ISSUE TITLE
plugin Zwave : module ZMNHCA2 always at 100%

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#467]
![image](https://user-images.githubusercontent.com/16737541/39713006-67634a2a-5225-11e8-87d1-b9d749a5d5c1.png)

After entering 0% at the switch multilevel, the value is always 100%

**Comment by jano42** [comment]
Please check device configuration.
There may be items to change to make it work.
Please provide screenshot

**Comment by jmberhault** [comment]
I have send you some logs last week have you look at them ?

**Comment by jano42** [comment]
Is that issue still active ?

Maybe fixed with Yadoms 2.2, or this could be explained by a sleeping device (modifications from yadoms to device may take one or two hours to be applied. this is due to sleeping device which wake up only 1 time per hour)

I close the issue; because I think it is fixed
