### ISSUE TITLE
Event misses when the start() function of a timer is used wihout stop.

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#474]
This function will create a periodic timer every 30s, qith the first event in 30s :

m_periodicSamplingTimer = api->getEventHandler().createTimer(kSamplingTimer,
                                                                shared::event::CEventTimer::kPeriodic,
                                                                boost::posix_time::seconds(30));

If in the following code, we have :

...
m_periodicSamplingTimer->start();
...

The first event 30s later is not fired. The next one will be 1mn since the creation of the timer.

**Comment by sgallou** [comment]
It is a bad usage of perdiodic timer : a periodic timer created with a provided time is started at creation as documented in EventTimer.h. If you want to delay timer start, don't provided time at creation, but at start.
Starting an already running periodic timer makes no sense for me.

So the only modification I see is to log a warning when user try to start an already running perdiodic timer. Somthing like "Trying to start already running periodic timer, ignored".

**Comment by sgallou** [comment]
Fixed by adcb3354f1ec78dd27d4bef42e4b52d853be5ab0 (ignore multi-starts on perdiodic timer)
