### ISSUE TITLE
Upgrading from 2.0.2 to 2.1.0 beta 2

### ISSUE THREAD

**Issue by KptnCavern** [Yadoms/yadoms#476]
I tried to upgrade Yadoms from 2.0.2 to 2.1.0 beta 2, but it failed during the upgrade of the database.
Noticed that after having suppressed the database, Yadoms worked again (but I needed to configure everything again).

You'll find the log below.

17:20:03 : Supervisor : [Information] : Upgrading database (4.1.0 -> 4.2.0)...
17:20:03 : Supervisor : [Fatal] : Failed to upgrade database (4.1.0 -> 4.2.0) : Invalid parameter timezone : No such node (timezone)
17:20:03 : Supervisor : [Fatal] : Rollback transaction
17:20:03 : Supervisor : [Error] : Fail to load database (upgrade error) :
Failed to update database
17:20:03 : Supervisor : [Error] : Supervisor : unhandled exception Fail to load database

**Comment by jano42** [comment]
I've also the same problem !

The timezone column seems not to be added in update script -> @sgallou

**Comment by sgallou** [comment]
Garde ta base d'origine, que je puisse tester, stp.

**Comment by sgallou** [comment]
Fixed by 391744c5742ecc97c106e2ff0d837e6a79d444b8
