### ISSUE TITLE
plugin RFXCOM : CARTELECTRONIC Encoder Protocol => add the possibility to select good profils to absolute counter

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#477]
At this time the protocol is already created to the RFXCOM plugin, but values are registered with absolute historizer CCounter.

The goal, is to propose to the user, when the device is discovered, the possibility to choose between theses 3 followings equipments in the device configuration : 
- energy counter where 1 pulse = 1 Wh. (historizer = CEnergy)
- water counter where 1 pulse = 1 liter. (historizer = CVolume ; Value /1000)
- water counter where 1 pulse = 1/4 liter. (historizer = CVolume ; Value /4000)

After set the configuration, values are displayed to the correct unit to the user, with no need to convert the value with scripts.

**Comment by sgallou** [comment]
Need also to add gas counting (1 pulse for 0,1 m3 and 1 pulse for 0.01m3)

**Comment by sgallou** [comment]
Fixed by 3ead6c9547788611a1e6b11f85a74bfb68b9db3f
