### ISSUE TITLE
ZWAVE - Configuration display error

### ISSUE THREAD

**Issue by Jerome2607** [Yadoms/yadoms#482]
Bonjour,
Je possède une sirène Zwave 
Lorsque j'affiche la configuration, il y a un problème de taille sur certains champs.

class: 0x70 COMMAND_CLASS_CONFIGURATION_V2 :
Les champs "Sound/Light Index 1" --> "Sound/Light Index 6" sont codés sur 18 bytes, or l'affichage ne remonte qu'un seul byte
[Benext_Alarm_Sound_MANUAL_US.pdf](https://github.com/Yadoms/yadoms/files/2037255/Benext_Alarm_Sound_MANUAL_US.pdf)
...

Ci joint la doc de mon device dans laquelle apparait la taille des champs (page 6 et 7).

Cordialement,
Jerome

**Comment by sgallou** [comment]
For next times, use english for issues, please.

Sébastien

**Comment by jano42** [comment]
I will check around OpenZwave. This is the library we use to control zwave and provide us all devices configuration/capabilities.
I'll look for your alarm device and if needed report the issue to openzwave.

**Comment by jano42** [comment]
Is this issue still active with last Yadoms version (2.2) ?

**Comment by Jerome2607** [comment]
Field is on 18 bytes.
Is it possible to enter number in hexadecimal instead in decimal ?
Because in decimal, number is too long...
(After 20 digits, decimal number is truncate)

**Comment by jano42** [comment]
In current ZWave library, the 18bytes field is treated as a single byte.

I've create an issue for that, and I have the answer: I have to update configuration file manually...

**Comment by jano42** [comment]
Fixed in develop branch. Will be available on next release
