### ISSUE TITLE
ZWAVE : COMMAND_CLASS_USER_MODE can't be set

### ISSUE THREAD

**Issue by Jerome2607** [Yadoms/yadoms#484]
For the device "Mini Keypad RFID", User_Mode can't be set.
See joigned user manual.
Class 0x63 COMMAND_CLASS_USER_MODE

**Comment by Jerome2607** [comment]
join user manual
[wt-rfid-eu_zipato mini_keypad_rfid_+_z-wave_user_manual.pdf](https://github.com/Yadoms/yadoms/files/2046816/wt-rfid-eu_zipato.mini_keypad_rfid_._z-wave_user_manual.pdf)
al

**Comment by jano42** [comment]
Hi Jérôme,

I've worked with your device and now its working.
I'll publish my modifications probably on next week; and I should give you back the reader.

a+

**Comment by jano42** [comment]
Fixed in develop branch
