### ISSUE TITLE
Linux compilation : cmake_linux.sh

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#490]
the following script in cmake_linux.sh search the key ALTERNATIVE_CMAKE_ROOT, even if the key is not activate. We have to search if this one is commented with '#'. 

_getCMakeExecutable () {
local cmakePath=$( grep -oP 'ALTERNATIVE_CMAKE_ROOT[[:space:]]\"\K.*(?=")' ../sources/CMakeListsUserConfig.txt )
if [ -z "$cmakePath" ]
then
echo cmake
else
echo $cmakePath/bin/cmake
fi
}
cmake_executable=$(getCMakeExecutable)_

**Comment by sgallou** [comment]
Fixed by b74d19a891c0ad3aa3d8e3e9b65332c30ed50dad
