### ISSUE TITLE
Plugin fails to start

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#492]
When Yadoms starts (here, restart after update to 2.1.0 version), sometimes some plugins fail to start, so Yadoms take much time to finish its start and plugins must be manually started.
See logs

[plugin-10.log](https://github.com/Yadoms/yadoms/files/2096809/plugin-10.log)
[plugin-11.log](https://github.com/Yadoms/yadoms/files/2096810/plugin-11.log)
[yadoms.log](https://github.com/Yadoms/yadoms/files/2096811/yadoms.log)
[plugin-8.log](https://github.com/Yadoms/yadoms/files/2096812/plugin-8.log)

**Comment by jmberhault** [comment]
This issue is the same as this one : https://github.com/Yadoms/yadoms/issues/442

**Comment by sgallou** [comment]
Fixed by a60c902ba162725de2b773e8ace8fb26df84589a
