### ISSUE TITLE
Cannot create or remove a rule from the automation menu

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#496]
I receive each time "cannot create ..." / "cannot delete ..."

**Comment by jmberhault** [comment]
First problem: for an unknow reason, the rule is present into the datablase, but not into the directory : 

![image](https://user-images.githubusercontent.com/16737541/41507666-99ecf5c2-7237-11e8-802a-7590c06503fa.png)

the directory /scripts/17 doesn't exist.

Yadoms logs are the following : 

13:48:39 :  : [Trace] : Rest request : [GET] : /rest/automation/rule
13:48:40 : Websocket connection : [Trace] : Rest request : [DELETE] : /rest/automation/rule/17/log
13:48:40 : Websocket connection : [Trace] : [SEND] message 9 to interpreter Python 2.7
13:48:40 : Websocket connection : [Debug] : Send purgeScriptLog to interpreter Python 2.7
13:48:41 : interpreter.yPython27 : [Information] : Close message queues
13:48:41 : interpreter.yPython27 : [Information] : Script 16 is stopped
13:48:41 : interpreter.yPython27 : [Information] : Script 15 is stopped
13:48:41 : interpreter.yPython27 : [Information] : Script 13 is stopped
13:48:41 : interpreter.yPython27 : [Information] : Script 10 is stopped
13:48:41 : interpreter.yPython27 : [Information] : Script 9 is stopped
13:48:41 : interpreter.yPython27 : [Information] : Script 5 is stopped
13:48:41 : interpreter.yPython27 : [Information] : Script 4 is stopped
13:48:41 : interpreter.yPython27 : [Information] : Script 3 is stopped
13:48:41 : interpreter.yPython27 : [Information] : Script 2 is stopped
13:48:41 : interpreter.yPython27 : [Information] : Script 1 is stopped
13:48:41 : interpreter.yPython27 : [Error] : yPython27 crashed with exception : boost::filesystem::directory_iterator::construct: No such file or directory: "logs/scripts/17"
13:48:41 : interpreter.yPython27 : [Information] : Interpreter Python 2.7 is stopped with error (2) : yPython27 crashed with exception : boost::filesystem::directory_iterator::construct: No such file or directory: "logs/scripts/17"
13:48:41 :  : [Trace] : Rest request : [GET] : /rest/automation/rule
13:48:43 : Websocket connection : [Trace] : Rest request : [GET] : /rest/automation/rule

We should be able to delete the rule (in error) even if this one doesn't exist physically. I don't why this one doesn't exist and this information is not coherent, but we should be able to delete it.

**Comment by jmberhault** [comment]
No logs for the refuse to create a script

**Comment by jmberhault** [comment]
Can't reproduce with Windows, with the same database ... Should be tested with an other pi, or with Linux.

**Comment by jmberhault** [comment]
more information in browser console : 
Impossible de supprimer la règle Essai Google Calendar. boost::filesystem::rename: Permission denied: "scripts/locals/rule_17", "scripts/locals/rule_17.bak"

**Comment by jmberhault** [comment]
more information from the browser console for the rule creation : 
utility.js:90 Impossible de créer la règle Essai. Unable to create directories

**Comment by sgallou** [comment]
It seems that original problem comes comes from a corrupted SDCard.
But we have try to recover a such situation.

**Comment by sgallou** [comment]
Closed by 9d6d2975a555f15dc9e8c62352e6af8d9ffcec5b
