### ISSUE TITLE
[web client - page devices] click fastly on the button "Create a device" generate more than 1 sub page

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#499]
![image](https://user-images.githubusercontent.com/16737541/41621012-c00e6cba-740b-11e8-9acc-51723b9db168.png)

**Comment by jmberhault** [comment]
This trouble is right also for the button create a rule.

**Comment by jmberhault** [comment]
It's the same for the button create a recipient. Can't reproduce with "create a plugin"

**Comment by sgallou** [comment]
Probably same cause than #498
