### ISSUE TITLE
Yadoms wait Plugins Status Running before execute scripts

### ISSUE THREAD

**Issue by jano42** [Yadoms/yadoms#51]
With the RFXCOM plugin, the "running" state could be appears only after 1 minute (At this moment). This could be right also for any plugins with a long time to initialize.
During this time, python scripts are running before this state, and some commands could be trashed during this time.

Yadoms could manage this, and execute the script only when concerned plugins are in the state "running".

Reported by: jmberhault

**Comment by sgallou** [comment]
wont-fix status, see above
