### ISSUE TITLE
[switch] Bad behaviour with dimmable keyword

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#520]
Use of only one keyword.
Switch v1.1.1.

Click on "1" button doesn't highlight itself. "0" button works.
![sw1](https://user-images.githubusercontent.com/6855339/49902633-c4fe8780-fe64-11e8-8a03-1ba1500ce6b4.gif)

Not tested with multiple keywords, but need to be carefully tested :
- multiple dimmable keywords
- multiple on/off keywords
- mixed on/off and dimmable keywords

**Comment by jano42** [comment]
Fixed in develop branch
