### ISSUE TITLE
[Chart] <1 values not supported

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#521]
In this case, I try to display a value from 0 to 0.2 seconds for the Ping (precision is set to 3 in th widget configuration) :

![image](https://user-images.githubusercontent.com/6855339/50121022-c27ea200-0257-11e9-80af-ae45f4a9c455.png)

**Comment by jmberhault** [comment]
For this point, I have to handle duration into the chart. It's not the case, so duration are traited as long in seconds, with no floating point.

**Comment by sgallou** [comment]
This issue concerns only duration values, because duration format "hh:mm:ss" is not appropriated.
Should be a number of seconds, coded in float. Refactor needed.

**Comment by jmberhault** [comment]
The refactor will not accept the old format. The old format is only display with hours. 
The migration should transform all format in seconds.
A unit should be added to the duration capacity. the refactor will impact also some plugins and the numeric widget

**Comment by sgallou** [comment]
Server now manages duration as double in seconds (f637238940c875baa82178003852edab3892d701).
Need to update webclient and/or some widgets.
