### ISSUE TITLE
GUI loading is slow

### ISSUE THREAD

**Issue by jano42** [Yadoms/yadoms#53]
2 sources of slow :
- at page loading
- at dashboard opening

Some way to investigate :
- when opening dashboard, all plugin locale files are loaded, not only for the current langage
- when opening dashboard, some plugin locale files are loaded 2 times
- some files could be loaded when user ask (ie blockly depandancies when opening blockly editor) or in background

Reported by: sgallou

**Comment by lgm42** [comment]
Here the loading timing before any modification:
![image](https://cloud.githubusercontent.com/assets/6039130/12718233/72f27064-c8ed-11e5-9fb8-693875b1d17f.png)
