### ISSUE TITLE
EnOcean - wrong equipment creation

### ISSUE THREAD

**Issue by Jerome2607** [Yadoms/yadoms#530]
Wrong equipments appear in equipment list.
These equipments don't exist physically and have not associated data.

See joined Screenshot:
![capture d ecran 2019-01-10 a 19 16 21](https://user-images.githubusercontent.com/39408484/50989001-7fd67f80-150e-11e9-96b5-9e11841a18e1.png)

See joined logFile : 
23:18:58 : mainThread : [Information] : New device declared : 
23:18:58 : mainThread : [Information] :   - Id           : 000004F0
23:18:58 : mainThread : [Information] :   - Profile      : Unknown. No historization until user enter profile.

[plugin.log](https://github.com/Yadoms/yadoms/files/2746613/plugin.log)

**Comment by Jerome2607** [comment]
I have the same with ZWave equipment : 
![capture d ecran 2019-01-10 a 19 35 47](https://user-images.githubusercontent.com/39408484/50989198-fa070400-150e-11e9-99f8-75f7645d9430.png)

**Comment by sgallou** [comment]
Need a log in trace log level.

**Comment by Jerome2607** [comment]
See joined log file (in trace level).
See device nb : 0034EE74

Remark : This device is appears when I've used Enocean remote control.

[plugin.log](https://github.com/Yadoms/yadoms/files/2752302/plugin.log)

**Comment by sgallou** [comment]
Message containing ID 0034EE74 is fully valid (Both CRC are OK).
So can not ignore this message.

Maybe should we disable automatic pairing. To be discussed...

**Comment by Jerome2607** [comment]
New devices appears : 
![capture d ecran 2019-01-14 a 20 01 51](https://user-images.githubusercontent.com/39408484/51134235-47e57a00-1837-11e9-8ef9-2dc359e30cd2.png)

Log File : 
[plugin.log.20190113154614999.gz](https://github.com/Yadoms/yadoms/files/2756674/plugin.log.20190113154614999.gz)

**Comment by sgallou** [comment]
Fixed by 5b12d1761de211e782b3bfad7151a1f8310a3869
