### ISSUE TITLE
RFXCom plugin crashes at startup

### ISSUE THREAD

**Issue by dgateau** [Yadoms/yadoms#534]
At startup, the RFXCom device fails to initialize (timeout to answer). 
Most probably linked to increasing number of errors "Summary computing task : [Error] : Error in computing summary values" that overload the PI resources.
[yadoms.log](https://github.com/Yadoms/yadoms/files/2805159/yadoms.log)

**Comment by sgallou** [comment]
It sounds strange as server seems to have enough time to process the message (I think that Summary task error doesn't have effect).
Please provide log in trace level to check if the message was lost or if task managing the answer is freezed (or maybe if the answer was lots).

**Comment by sgallou** [comment]
Seems to happen when machine very loaded. Can you check your CPU load when Yadoms is running ?
Don't you have scripts doing polling without sleep times ?
