### ISSUE TITLE
Graph doesn't work with new version (2.2.0-beta.4)

### ISSUE THREAD

**Issue by Jerome2607** [Yadoms/yadoms#540]
I've installed last version : 
Yadoms : 2.2.0-beta.4
Graph widget : 1.2.0-rc.2

After that, graph doesn't work : 
When you select "tout" on graph, there is no data, if you select "horaire", it's Ok.

I've try to go back another version for graph widget (1.1.1), but it is the same...

**Comment by jmberhault** [comment]
The problem looks to appears with Yadoms 2.2.0-beta.4. Yadoms return some request errors at the launch of the widget with the "all" button.

We have to investigate more ...

**Comment by sgallou** [comment]
Fixed by 247f5a6247e23e24a4bdcc24add0f46fe26786d8
