### ISSUE TITLE
Add a Python 3.x script interpreter

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#543]
Python 2.7 seems to become obsolete, add a Python 3.x script interpreter

**Comment by sgallou** [comment]
Developed but not tested.
Need to update build systems :

- Update CMake to last version
- In CMakeListsUserConfig.txt, add :
   - set(PYTHON27_ROOT "xxxx")
   - set(PYTHON3_ROOT "xxxx")
   - keep :  set(PYTHON_ROOT "xxxx")
- Optional : update other dependencies (boost, poco, protobuf, etc...)

**Comment by jano42** [comment]
How to update CMakeListsUserConfig.txt when using dpkg mode ?

````sh
set(PYTHON_USE_PKGCONFIG ON)
set(PYTHON_USE_SOURCES OFF)
````

**Comment by sgallou** [comment]
I think you can't use dpkg mode with the both python interpreters...

**Comment by jano42** [comment]
Fixed in develop branch

**Comment by sgallou** [comment]
Interpreters (2.7 & 3) doesn't work on Linux and Mac. Should we :

- Embed Python with Yadoms ? (be careful to cross-build, and don't forget to provide pip)
- Add .ini file to let user to specify python executable path ?

**Comment by jano42** [comment]
Both !

One to be sure all is working as expected in nominal case.
The second, if too hard to embed python (some obscur platform) or user want to test another version of python

**Comment by sgallou** [comment]
Add .ini (specific to interpreter) to provide Python executable folder, and use it by default.

**Comment by sgallou** [comment]
Specific ini file to interpreter is problematic : this kind of file can not be backuped (no saved 'data' folder like for plugins), and isolated in yadoms executable hierarchy.
I suggest to add the forced paths in the general yadoms.ini file.

**Comment by jano42** [comment]
Yes it easier
In yadoms.ini file you could provide a section of config for interpreters

For example:
```

[interpreter/python2]
pyhtonPath=.....

[interpreter/python3]
pyhtonPath=.....
```

**Comment by sgallou** [comment]
Fixed by 9454b69d6ff001edd6ea678c7a19ba31c9c7a235
Need to be tested on all platforms

**Comment by oben01** [comment]
python 2.7 and python 3 are installed by default in mac OS Catallina.
test python 2.7   ==> OK
test python 3.7.3 ==> OK
blokly                     => OK

tests are made from develop branch

**Comment by oben01** [comment]
@sgallou do you need me to install another python 3 version by hand and test it ?

**Comment by sgallou** [comment]
> @sgallou do you need me to install another python 3 version by hand and test it ?

No, 3.7.3 is OK. Thanks for your test.
