### ISSUE TITLE
Specify python path

### ISSUE THREAD

**Issue by jano42** [Yadoms/yadoms#547]
Make scriptInterpreter configurable, with the ability to specify the python path.

In some cases with multiples python installs ( x86, x64,... in different path), the chosen path is not the good one.

**Comment by sgallou** [comment]
In normal use of Yadoms, the server is installed on a dedicated machine (RasperryPi for example), so multiple installations of Python make no sense.
Actually, Yadoms search Python here :

- Linux / MacOs : only on the path
- Windows :
  - on the path
  - from path set in registry at SOFTWARE\\Python\\PythonCore\\2.7\\InstallPath
  - from path set in registry at SOFTWARE\\Wow6432Node\\Python\\PythonCore\\2.7\\InstallPath
  - from C:\python27
  - from %ProgramFiles%\python27
  - from %ProgramFiles(x86)%\python27

So you can avoid making a particular installation of Python to be detected by Yadoms, installing it where Yadoms can't find it.

**Comment by jano42** [comment]
The only thing to check is compatiblity with Python 64 bits !

Yadoms is built with 32 bits environnement. (with Python 32). Is it working
with Python 64 installed on dedicated server ?

Le lun. 4 mars 2019 à 11:34, Sébastien Gallou <notifications@github.com> a
écrit :

**Comment by sgallou** [comment]
It was not tested with Python 64 bits (as sayed in [this wiki page](https://github.com/Yadoms/yadoms/wiki/For-Windows)).
But maybe it works... Need to be tested (by someone that have a Python 64 bits version installed ;-) )
