### ISSUE TITLE
Plugin : all dates are displayed as "invalid"

### ISSUE THREAD

**Issue by dgateau** [Yadoms/yadoms#548]
(Yadoms v2.2)
All the plugins that include the date of the last acquisition reporte the display as "invalid".
![invalid dates](https://user-images.githubusercontent.com/29263034/53655478-9bc5ea00-3c50-11e9-8eea-d77714449386.png)
![invalid dates2](https://user-images.githubusercontent.com/29263034/53655480-9c5e8080-3c50-11e9-862f-a248e1d2a095.png)

**Comment by dgateau** [comment]
Additional information:
- still present after a reboot.
- present on new/added widget
- present after removing and restoring "display date of last update" checkbox for an existing plugin

**Comment by sgallou** [comment]
It was due to an old numeric widget version. Fixed after upgrade to last widget version.
Due to a modification on widgets management Yadoms-side, most of widget must be upgraded to latest versions.

**Comment by sgallou** [comment]
Closed by f15689b14d59b31b615db4e3de84c5da25308ca8
