### ISSUE TITLE
Numeric display : unit is truncated

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#552]
See screenshot :
![image](https://user-images.githubusercontent.com/6855339/54229817-60a3a080-4505-11e9-8b7e-0ea8f0992cf6.png)

Widget is configured in auto-scale.

Refresh page or cache doesn't help.

**Comment by jmberhault** [comment]
fixed by commit 3ddad4f19135a26133ef7a675958d4d36eb05981
