### ISSUE TITLE
plugin enOcean : module EEP D2-05-00

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#557]
- The translation for one field is not done.

![image](https://user-images.githubusercontent.com/16737541/56673332-5c4bd500-66b8-11e9-9e9c-43ab7da14fb3.png)

- The ordering open/close is reverse through Yadoms comparing to the pairing done with an other enOcean. The state has been checked, true => open / false => down. And Yadoms do the exact reverse.

- Values in column "values" never change.  Even if I set a new value through Yadoms.

**Comment by sgallou** [comment]
First part (blind direction inverted) fixed by 821e645b393235819a0cb98720166a59873923bc
Second part not reproduced with Yadoms 2.3.0-beta.3
