### ISSUE TITLE
[Update] from yadoms 2.2.1 => 2.3.0-beta.3

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#561]
When update from 2.2.1 to 2.3.0-beta.3, yadoms web client stay stucked to this screen. The only way to restore yadoms is to press F5.

![Yadoms stay stucked to the waiting page](https://user-images.githubusercontent.com/16737541/57582048-647d8000-74c0-11e9-8c88-5d4334b1cb64.png)

**Comment by sgallou** [comment]
Fixed by f7c5fd09b0081ead683ffb5cfb5e68dc5b9e1072
