### ISSUE TITLE
plugin SMSDialer no more available

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#577]
For Raspberry Pi plateform, the plugin SMS Dialer is not available for the revision 2.2.1 (Gammu doesn't compile any more)

**Comment by sgallou** [comment]
Need to update build system :

Install gammu :
`apt-get install gammu`

In CMakeListsUserConfig.txt :
`set(GAMMU_ROOT "xxx")`

"xxx" must contain :

- an `include` folder where is gammu.h
- an `build/libGammu` folder where is libGammu.a

**Comment by jano42** [comment]
Fix in develop branch (with new docker images)
