### ISSUE TITLE
Black screen when scroll down with a smartphone

### ISSUE THREAD

**Issue by jano42** [Yadoms/yadoms#58]
When a phone with chrome is hold vertically, a black screen is displayed when scrolling down. This have not been tested with windows for the server.

The back of submenu could not also be displayed ( devices, ...).

When the phone is hold horizontally, the problem doesn't appear.

the problem appear also with a touchpad in a vertical position.

Reported by: jmberhault

**Comment by jano42** [comment]
Not reproductible on IOS 9 (iphone 4)

**Comment by jmberhault** [comment]
Not reproducible with the last revision of today. I close this issue.
