### ISSUE TITLE
[Web site] Add smartscreen warning for Windows executable

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#583]
Windows Smartscreen says that Yadoms is not recognized.
[See this post](https://codedead.com/?p=2224)
As we can't buy a certificate (too expansive !), add an warning when user want to download Yadoms for Windows.

**Comment by jano42** [comment]
A free certificate from globalsign has been requested (https://www.globalsign.com/en/ssl/ssl-open-source/)
Waiting for a few days and acting depending on the Globalsign answer.

**Comment by jano42** [comment]
Globalsign do not provide code signing certificates for free. (even for opensource projects).

**Comment by jano42** [comment]
To remove SmartScreen message we should:

- sign our application with code signing certificate
- wait for having a good reputation (the more valid installation are done, the more our reputation willl grow)

So we will just add a warning on download page

**Comment by jano42** [comment]
Fixed by adding a webstie warning
