### ISSUE TITLE
Scripts/Plugins new and old code

### ISSUE THREAD

**Issue by jano42** [Yadoms/yadoms#590]
I think the issue could mostlt appear in development environment.

### Context

I've a yadoms working with some scripts (id=2 and 3)
I delete the yadoms.db3 to make other tests.
When I create a Blockly script, it take the id2; but as the folder has not been deleted, then when I want to save it, then it fails. But the script is created and when I execute it, it runs the script in folder (from old installation)

### Idea

To avoid this (may occurs in some obscur cases), the idea is to get the first free Id without any existing folder (if id 3 is ok in database but with such a folder then try number 4,...)

**Comment by jano42** [comment]
This is also available for plugins (with data and logs folder)

**Comment by jano42** [comment]
Another way to fix it, when creating database (first start) then clear script, plugins data and logs content

**Comment by sgallou** [comment]
Database should not be deleted alone.
It's a pure development context behaviour.
If you absolutely want to fix it, I prefer your last proposal : deleting all related data if database doesn't exist at startup.

**Comment by jano42** [comment]
But in case of database corruption (may occurs on rpi sdcard...)
May the user want to restore all its scripts...

**Comment by sgallou** [comment]
User will restore a full backup.
It makes no sense to restore only a part of user data. And risky.
