### ISSUE TITLE
[ZWave] Some boolean keyword declared with non-standard capacity name

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#592]
For Example, with an HSCP02 motion detector, "Detection" keyword is declared with a non-standard capacity "Sensor" instead of the standard one "switch". So standard widgets can not be used (indicator widget in this case).
In opposite, for battery level, the standard capacity "batteryLevel" is well used.

**Comment by jano42** [comment]
Fixed in branch ozw16
