### ISSUE TITLE
web client : desactivated widget

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#594]
desactivated widgets are not grey.

**Comment by sgallou** [comment]
When loading a page containing some widgets which reference a deleted device, concerned widgets are well greyed.
But after deleting a device from the devices page of configuration panel, and closing the configuration panel, the current displayed page is not reloaded and widget is not grayed.
Do we have to reload the page after closing configuration panel ?

**Comment by sgallou** [comment]
Closed by 0e48f9ebf9c21d4089f468b53f0244eb0ebb8f9c
