### ISSUE TITLE
Database : crash after some times due to the database

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#598]
**Describe the bug**
yadoms application crashed with a database that looks not ok (after some times, initialy working).
After removing the database, yadoms works properly.

**Which environnement**
1. Yadoms version
v2.3.0
2. Host hardware (computer, raspberry...)
Pi
3. OS and Version (Windows 10, Raspbian Stretch April 2019,...)
Strech

I will send you the database directly in a separate channel. Start the application with the database, and yadoms should crash (it's the case under raspberry)

**Comment by sgallou** [comment]
Probably still a SDCard problem. Database is pretty big (> 500Mb), and oldest data have almost 1 year (installation with 75 devices).
We know that in this case, SDCard doesn't work more than a few month.

I run Yadoms with your database on a PC for some hours without problem (but without your devices). I think error occurs at some write operation in database (at device acquisition).

Please use a hard drive.
