### ISSUE TITLE
[Plugins] - update workflow

### ISSUE THREAD

**Issue by jano42** [Yadoms/yadoms#610]
I would be nice for a plugin to be notified on update.

This could be issued by something like this:

- one event (beforePluginUpdate) : so the plugin could make some operations before updating
- one event (afterPluginUpdate) : to make operations before plugin restart after update

This could be very appreciate in case of a plugin which stores many data in its dedicated folder.
For example, ZWave stores the OpenZwave library context (2~3 files), and those files must be deleted before starting a new OpenZWave version.
Actually we do not have any information about updates.

The **before update** is not really important. (most of cases the previous version do not really know what to do to support the new one)
The **after update** is really the most important. This is always the new version which knows how to work after an update.

**Comment by sgallou** [comment]
I think you can manage this at plugin level, by recording running version somewhere in your data folder, and read it back at plugin start.
The need is for me very specific, so I prefer to not modify plugin API for this function.

**Comment by jano42** [comment]
Issue no more useful. Close.
