### ISSUE TITLE
The file yadoms.ini is not copied under ..\builds\DEBUG

### ISSUE THREAD

**Issue by oben01** [Yadoms/yadoms#632]
The file yadoms.ini is not copied under ..\builds\DEBUG

1. Yadoms version : 2.4.0-beta.1
2. Host hardware : computer 
3. OS and Version : Windows 10

**To Reproduce**
Build yadoms

**Comment by jano42** [comment]
Not a debug, it is volontary.
Having an ini file is responsibility of developer. (so never overwritten,...)

Only packaging get the yadoms.ini
