### ISSUE TITLE
ComboBox section remain in French when using English as default Language

### ISSUE THREAD

**Issue by oben01** [Yadoms/yadoms#648]
When using English as default Language.
I created a new LametricTime plugin, all sections are in english ==> OK 

![plugin_configuration_paring_mode_auto](https://user-images.githubusercontent.com/22369027/71196435-5e3e5600-2290-11ea-9392-995384ddf21e.PNG)

then I switched to Manual Pairing mode and all sections remain in French ==> KO

![plugin_configuration_paring_mode_manual](https://user-images.githubusercontent.com/22369027/71196976-e45a9c80-2290-11ea-9cbc-a7a2e2a13380.PNG)

The Manual section in the file locales/en.json is fully translated

**Comment by sgallou** [comment]
Fixed by cc9d36cce3457036960c7063729ea2ff1840f998 (bad JSON in LametricTime plugin)
