### ISSUE TITLE
[Stream Deck]  manage Continuous integration & Cross

### ISSUE THREAD

**Issue by oben01** [Yadoms/yadoms#665]
*manage Continuous integration for openCv and hidapi  ==> travis, appveyor  and maybe regenerate Docker Container. 
*Cross platform opencv & hidapi

**Comment by sgallou** [comment]
Build now on Pi
Need to disable plugin for Synology

**Comment by sgallou** [comment]
Fixed by 8f4aea29343c5d90656d8ddca31a78555da7050a
