### ISSUE TITLE
Last state not updated when using a CEvent keyword

### ISSUE THREAD

**Issue by oben01** [Yadoms/yadoms#668]
Am using CEvent in my StreamDeck plugin, when a key is pressed the last State is not updated (even when the page is refreshed)

Which environnement

1. Yadoms version : 2.4.0-beta.1
2. Host hardware : computer
3. OS and Version : Windows 10

**To Reproduce**

Pull feature/StreamDeck 

1. Create a new streamDeck plugin
2. Create a script 
![script](https://user-images.githubusercontent.com/22369027/78679505-970b4500-78ea-11ea-9dad-6dfe236dbdc5.PNG)

``` python
# yMain is the script entry point, called by Yadoms
#Imports helpers
import scriptUtilities
import time


def yMain(yApi):
   print ('Script started')
   while True:
      # Wait for event block -------> START
      endOfLoop = False
      wantToBreak = False
      wantToContinue = False
      while endOfLoop != True :
         totalKeywordsToListen = [66]
         waitForEventResult = yApi.waitForEvent(totalKeywordsToListen, False)
         keywordId = waitForEventResult.getKeywordId()
         outVar = waitForEventResult.getValue()
         if waitForEventResult.getType() == scriptUtilities.WAITFOREVENT_KEYWORD and keywordId == 66:
            print ('pressed')
            endOfLoop = True
   
      # Manage break/continue inside waitForEvents
      if wantToBreak:
         break
      if wantToContinue:
         continue
      # Wait for event block -------> END

```

3. Pressed the Key
We expect that we write pressed in rule log ==> **OK**
![log](https://user-images.githubusercontent.com/22369027/78681397-f8341800-78ec-11ea-9e03-f48984f5c85d.PNG)

We expect also that the Last state to be updated ==> **KO**
![states](https://user-images.githubusercontent.com/22369027/78681869-932cf200-78ed-11ea-9a57-38869e18d476.PNG)

**Comment by sgallou** [comment]
Fixed by 10cfa16a87e491c03557d4f2240fc3f5b82720cc
