### ISSUE TITLE
HTTP devices auto-detection

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#680]
Move the ssdp client (from LametricTime plugin) into shared, to provide easy http devices auto-detection for all plugins.
Currently written using boost, first rewrite it to use libcurl.

**Comment by oben01** [comment]
Leave boost and move it to shared

**Comment by sgallou** [comment]
Closed by 16476906c0ae6279fff4f3fcb71ff3f29f5ed5cc
