### ISSUE TITLE
[2.4.0-beta.4] Indicator widget : icons list empty

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#688]
See on install image Yadoms-2.4.0-beta.4-Windows.zip

![image](https://user-images.githubusercontent.com/6855339/91632729-07724a00-e9e3-11ea-91f1-07ce86cee1ef.png)

**Comment by sgallou** [comment]
Seems to be an deployment issue, same issue exists on development version.

**Comment by jano42** [comment]
Not reproductible under Windows.
Please details running configuration (refresh cache. Maybe occurs due to your 2.5 dev version including some webfonts update)

**Comment by jano42** [comment]
OK reproduced.
It seems that it appears only the first time, because loading font icons takes too long.
A browser refresh fix the problem.

Need to investigate for fixing it by code

**Comment by sgallou** [comment]
Closed by 659130318ea35ed3f400d0ad6bee939f590b23dd
