### ISSUE TITLE
[FakePlugin] fileContent description is undefined + Asynchronous process title is not translated

### ISSUE THREAD

**Issue by oben01** [Yadoms/yadoms#703]
Which environnement

Yadoms version : 2.4.0-beta.4
Host hardware : windows
OS and Version : windows 10
Describe the bug
![async](https://user-images.githubusercontent.com/22369027/95656709-724d8f80-0b10-11eb-901c-1b80086c7a68.PNG)

**Comment by sgallou** [comment]
Fixed by 30e77c8ba67c6401e5d6bd1e92650230ba96c478
