### ISSUE TITLE
Bug/Critical : Crash when graph displayed

### ISSUE THREAD

**Issue by Jerome2607** [Yadoms/yadoms#708]
#@@2.4
@sgallou 
Ce n'est pas systématique, mais fréquent.
Lors de l'affichage des graphes, Yadoms s'arrête.
Rien de très explicite dans les trace
[yadoms.log](https://github.com/Yadoms/yadoms/files/5505390/yadoms.log)

**Comment by sgallou** [comment]
I was able to reproduce (2.4.0, commit 9c399dc8d1a5d2e7b485bc49e65cb6bf6932073e).
The crash comes from a heap corruption
![image](https://user-images.githubusercontent.com/6855339/99590646-ec194880-29ed-11eb-8e07-23774677baad.png)

when displaying a chart with a lot of acquisitions (ie temperatures on one month)

Crash occurs in sources\server\web\rest\service\Acquisition.cpp(306), when returning.

When decomposing this line of code into 2 lines like :
`
const auto test = CResult::GenerateSuccess(result);
`
`
return test;
`
shows that crash occurs when deleting `test` object

Descending into callstack says that crash occurs in CDatacontainer destructor (sources\shared\shared\DataContainer.cpp, line 117), when calling `operator delete(m_tree_allocator_initial_buffer);`

Can't investigate more as CDatacontainer insides is too tricky for me.

**Comment by sgallou** [comment]
Fixed by a58ac76253a61fd95d9cef3c7f3599c0a3b38ed4

**Comment by jano42** [comment]
@sgallou : potential fix

Could you try this dirty fix please (sources\server\web\rest\service\Acquisition.zip)
[Acquisition.zip](https://github.com/Yadoms/yadoms/files/5630699/Acquisition.zip)

I think I've identified the issue source (nothing relevant about element size).
If this dirty fix is ok, I'll provide a real good fix.
