### ISSUE TITLE
Dashboard bad displays

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#71]
- Wrong display at left
![image](https://cloud.githubusercontent.com/assets/6855339/12462638/af611082-bfbf-11e5-95c6-21b1ac0c1a9c.png)

- On this message box, message to select editor is wrong positionned
![image](https://cloud.githubusercontent.com/assets/6855339/12464192/1e17105a-bfc8-11e5-8eb4-1076c3d86b01.png)

**Comment by lgm42** [comment]
Closed in https://github.com/Yadoms/yadoms/commit/791a0b245f4a1f830a0d945007fa7d996b5b663e
