### ISSUE TITLE
[REST API] Yadoms crash with a runtime error when keywordId is not found in database

### ISSUE THREAD

**Issue by oben01** [Yadoms/yadoms#717]
I did a POST request to /device/keywordslastvalue with a Request Body as :
```json
{
  "keywordIds": [
    1,
    2,
    36
  ]
}
```
Yadoms crash with a runtime error when keywordId is not found in database (in my case 36)
Is that possible to send an empty fields insteed of crashing ? 🗡️

**Comment by sgallou** [comment]
Can not reproduce, from the feature/Swagger branch (commit f97278e0d5aed2331a2d215305245e12fa3857e8), only existing keywords are returned, and no crash happens. What is your Yadoms version/branch ?

![image](https://user-images.githubusercontent.com/6855339/104181978-00872980-5410-11eb-9637-f5aebfe7adce.png)

**Comment by oben01** [comment]
I get more information. Yadoms crash when lastAcquisitionValue is equal to NULL in database 
![LastAcquisition](https://user-images.githubusercontent.com/22369027/104958907-41171200-59d1-11eb-8514-de2537b155b3.PNG)
Yadoms crash at extractValueAsString in SQLiteResultHandler.cpp

**Comment by sgallou** [comment]
Closed by 30901045a436f3a88a7d3af394500f8def74adfc
