### ISSUE TITLE
RaspberryPi package embeds Curl includes and libs

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#726]
Inside RapsberryPI-Binaries package, we find :
- bin folder containing expected yadoms binaries, but also curl-config and curlpp-config (needed ?)
- include folder containing curl includes
- lib folder containing libCurl.a and curl cmake and pkgconfig related files

**Comment by jano42** [comment]
As Libcurl cmakelist contains "install parts", then its merged with our yadoms install cpack.
Need to integrate libcurl another way (using ExternalProject)

**Comment by sgallou** [comment]
Tried to build libcurl and curlpp using ExternalProject_Add in branch Fix#726_CurlEmbedding.
Still missing cross-compilation requirements injection.
@jano42 Can you check this, please ?

**Comment by sgallou** [comment]
Fixed by 89265ac104918961c807fe6a6e40e33c3b21e367
