### ISSUE TITLE
[Safari] "Invalid date"

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#730]
Only under Safari (at least OK under Chrome), meteo widget dates are displayed as "Invalid date".

![image](https://user-images.githubusercontent.com/6855339/114574646-b8c7a680-9c79-11eb-8a76-7ee7ce0ac54a.png)

Comes probably from getForecastDateTime in widgets\weather-multi\viewModel.js function, and [some workarounds are suggested here](https://stackoverflow.com/questions/4310953/invalid-date-in-safari).

**Comment by oben01** [comment]
@sgallou The server is not sending an ISO 8601 date format (Safari handle only iso 8601).
:white_check_mark: Correct : 1977-04-22T01:00:00-05:00
:x: Not correct : 2021-Apr-15 12:00:00
⚠️ However Chrome & Firefox are able to parse those false values.

We got two options here : 

- Server Side :
   - historize acquisations with suitable iso (User might need to remove/add his plugin ? give a user a script to play in his database ?)  
   - Patch those values before sending them to the client. (I prefer the first approch )
 - Client side : 
    - Patch the values. (We will need to report this fix to the next client version)

Client must always do less logical stuff... 
If the server solution is settled I let you do the fix 📟 

<img width="784" alt="Capture d’écran 2021-04-15 à 04 56 48" src="https://user-images.githubusercontent.com/22369027/114807703-2b827000-9da7-11eb-9a43-9f9473575164.png">

**Comment by sgallou** [comment]
Fixed by 646e59e09202593ef1a397c9e2541e6bebf90325
