### ISSUE TITLE
[RFXCOM] fusion of 2 equipments

### ISSUE THREAD

**Issue by KptnCavern** [Yadoms/yadoms#738]
**Describe the bug**
I've tried the fusion function of 2 equipments in the "Equipment" menu. The fusion haven't been a success

**Which environnement**
1. Yadoms version
The last one : 2.5

2. Host hardware (computer, raspberry...)
Raspberry pi + module RFXCOM + temperature captor Oregon scientific) 
3. OS and Version (Windows 10, Raspbian Stretch April 2019,...) 
Linux 4.19.42-v7+

**To Reproduce**
1.Have a captor Oregon scientific and get acquisitions. 
2. Configure some Widget to watch the values and a graph to see all the acquisitions. 
3. Change battery (or just remove it and replace it) : the captor will have a new name, losing acquisitions that had been made and widgets need to be reconfigure
4. Use fusion : fill in the new equipment and the old one
-> the widgets lose their configuration, obliging you to change them with the new equipment. 
No history is available and the widget display the message "no acquisition". 
It seems that the data of the new equipment replace the old one (deleting all the old values) and that the identity of the old equipment replaces the one of the new equipment. 
-> I've tried (after restoring the database) to inverse old and new equipment in the fusion menu :
It's better (the widget works directly without doing anything) and it makes acquisition again. But the acquisition of the elder captor has not been kept. 
**Expected behavior**
- widgets work directly with the new equipments without having to reconfigure them
- the new equipment gets all acquisitions made by the old one. 

**Screenshots**
I haven't kept screenshots but I can still restore database to make them if needed

**Comment by sgallou** [comment]
Fixed in 2.5.1-beta.1
Not fixed : crashed in chart widget making it to be deleted from page when configuration is wrong (ie : missing keyword).
