### ISSUE TITLE
impossible to download any image or installer from the website.

### ISSUE THREAD

**Issue by Paultergeist22** [Yadoms/yadoms#744]
**Describe the bug**

**Which environnement**
1. Yadoms version
2. Host hardware (computer, raspberry...)
3. OS and Version (Windows 10, Raspbian Stretch April 2019,...)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by oben01** [comment]
Hello Paul,

Thank u for reporting, we will take a look. For know u can download from github release https://github.com/Yadoms/yadoms/releases

**Comment by oben01** [comment]
@sgallou is that normal that we generate only one raspberry pi binary ? not anymore EN and FR binaries ?

**Comment by oben01** [comment]
@Paultergeist22 we fix all binaries link. We still waiting for @sgallou for raspberry images
