### ISSUE TITLE
To much time to open a web client

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#75]
Out of my home, it take around 40 seconds to open a GUI client.
Viewing Chrome logs, all libraries are loaded at first load :
* highstock take 2.67 s (for 206kb)
* canvas-tools take 845ms (for 56.8kb)
* blockly_compressed take 12.61s (930kb)
* wait-for-event take 528ms (30.8kb)
* ace.js take 4.22s (333kb)
* fr/en.json take 1s each, and 2 times (total of 4s)

Libraries should be loaded only if necessary (blockly, ace...).
Locale files should be loaded only for current language.

**Comment by lgm42** [comment]
duplicate in #53
