### ISSUE TITLE
Comments in Blockly are writable

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#79]
![image](https://cloud.githubusercontent.com/assets/6855339/12830184/49ec0fd8-cb8e-11e5-836b-209acde56060.png)

**Comment by jano42** [comment]
Is this a bug ? 
Comments are writable, because its the user which enter them.
I've just prepared a "template" with a comment to help user.

I think its not a bug. The user can also remove it.

**Comment by sgallou** [comment]
Ok, I understund it was just an help... I was confusing by the '?' icon.
