### ISSUE TITLE
Blockly broken : unable to create new rule

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#84]
It seems that the character ' (from "Cliquer sur l'icone engrenage bleu pour configurer les évènements" label) generate an error when validating a new Blockly rule.

Web console show :

> End of Automation rule edition : {"id":-1,"name":"test","description":"","interpreter":"Python","editor":"blockly","model":"","content":"<xml xmlns=\"http://www.w3.org/1999/xhtml\"><block type=\"infinite-loop\" x=\"87\" y=\"38\"><statement name=\"DO\"><block type=\"yadoms_wait_for_event\"><mutation storeinvariable=\"false\"><additional0 type=\"yadoms_wait_for_event_mutator_datetime_change\"></additional0></mutation><comment pinned=\"false\" h=\"89\" w=\"235\">Cliquer sur l'icone engrenage bleu pour configurer les évènements</comment><statement name=\"additionalInput_part2_0\"><block type=\"yadoms_log\"><value name=\"LogContent\"><shadow type=\"text\"><field name=\"TEXT\"></field></shadow><block type=\"text\"><field name=\"TEXT\">sdqds</field></block></value></block></statement></block></statement></block></xml>","configuration":"","autoStart":true}
> utility.js:87   Impossible de créer la règle test. near "icone": syntax error

It also sounds strange that a such label is recorded in the rule.

**Comment by jmberhault** [comment]
more complete logs : 
No workspace specified in workspaceToCode call.  Guessing. -> 

Blockly.Generator.prototype.workspaceToCode=function(a){a||(console.warn("No workspace specified in workspaceToCode call.  Guessing."),a=Blockly.getMainWorkspace());var b=[];this.init(a);a=a.getTopBlocks(!0);for(var c=0,d;d=a[c];c++){var e=this.blockToCode(d);goog.isArray(e)&&(e=e[0]);e&&(d.outputConnection&&this.scrubNakedValue&&(e=this.scrubNakedValue(e)),b.push(e))}b=b.join("\n");b=this.finish(b);b=b.replace(/^\s+\n/,"");b=b.replace(/\n\s+$/,"\n");return b=b.replace(/[ \t]+\n/g,"\n")};

![alarme - on - erreur 1](https://cloud.githubusercontent.com/assets/16737541/14233488/8e3cd374-f9ca-11e5-9e9d-ed19146bd3af.png)

![alarme - on - erreur 2](https://cloud.githubusercontent.com/assets/16737541/14233490/98c1e9ec-f9ca-11e5-90ad-e07ab1151680.png)

**Comment by jano42** [comment]
Fixed
