### ISSUE TITLE
Script Python : Size of internal messages

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#97]
1k for the size of static messages in the message queue looks to be not enough for script. Few times scripts return this error :

18:56:16 : yPythonScript.7cb63ad9-cc86-4ecc-8b04-788d96b9c64b : [Error] : CContextAccessor::sendAnswer : answer is too big
18:56:16 : yPythonScript.7cb63ad9-cc86-4ecc-8b04-788d96b9c64b : [Debug] : Close message queues

And the script doesn't work anymore.
This could append some hours after the starting of the script.

**Comment by sgallou** [comment]
Message size was increased.
